<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="bdb751e9-3902-4553-92ab-833f74f5e3a1">
  <actionCode id="9caf2c3c-a388-46fa-a93a-a0308a428ab5" isBeginAction="false" name="v_cus_id" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.VariableManagerActionCodeI">
    <link id="b6e5db0a-3b6e-45dd-beb4-e848ffa1c59f" executionType="OK" generationType="OK_KO" mandatory="1" targetId="5a007072-972f-4dd8-b106-303ae01a4f02"/>
    <metaDataLink id="70b7bf4d-f46c-4b14-b8f3-15e472ebd212" name="v_cus_id" target="resource.md#_SBnZgDXAEe2goMzdputf-Q?fileId=_RXCLcDXAEe2goMzdputf-Q$type=md$name=v_cus_id?" visibility="parent"/>
    <parameter id="957adf2f-12f6-4d7c-8f3c-752ee6d3265f" name="VAR_VALUE" type="String" value="80"/>
    <parameter id="db700ded-331f-49d8-958f-3312a7d54fce" name="VAR_OPERATION" type="String" value="SetValue"/>
  </actionCode>
  <actionProcessRef id="5a007072-972f-4dd8-b106-303ae01a4f02" isBeginAction="false" name="GenerateXMLCustomerDetails_var" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_3nZyQDXEEe2Sd_Hpmn5gBA?fileId=_3nZyQDXEEe2Sd_Hpmn5gBA$name=GenerateXMLCustomerDetails_var$type=map?"/>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=bdb751e9-3902-4553-92ab-833f74f5e3a1?" xmi:id="_qL4y4DXFEe2Sd_Hpmn5gBA" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_r3eyADXFEe2Sd_Hpmn5gBA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_r3jqgDXFEe2Sd_Hpmn5gBA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_r3kRkDXFEe2Sd_Hpmn5gBA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_r3kRkTXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_r3kRkjXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_r3kRkzXFEe2Sd_Hpmn5gBA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_r3kRlDXFEe2Sd_Hpmn5gBA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_r3kRlTXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_r3kRljXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_r3kRlzXFEe2Sd_Hpmn5gBA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_r3eyATXFEe2Sd_Hpmn5gBA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#9caf2c3c-a388-46fa-a93a-a0308a428ab5?fileId=bdb751e9-3902-4553-92ab-833f74f5e3a1$type=proc$name=v_cus_id?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r3eyAjXFEe2Sd_Hpmn5gBA" x="188" y="68"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_tcluoDXFEe2Sd_Hpmn5gBA" type="2003">
    <children xmi:type="notation:Node" xmi:id="_tcox8DXFEe2Sd_Hpmn5gBA" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_tcpZADXFEe2Sd_Hpmn5gBA" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_tcpZATXFEe2Sd_Hpmn5gBA" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_tcpZAjXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_tcpZAzXFEe2Sd_Hpmn5gBA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_tcpZBDXFEe2Sd_Hpmn5gBA" type="7004">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_tcpZBTXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_tcpZBjXFEe2Sd_Hpmn5gBA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_tcpZBzXFEe2Sd_Hpmn5gBA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_tcluoTXFEe2Sd_Hpmn5gBA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#5a007072-972f-4dd8-b106-303ae01a4f02?fileId=bdb751e9-3902-4553-92ab-833f74f5e3a1$type=proc$name=GenerateXMLCustomerDetails_var?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tcluojXFEe2Sd_Hpmn5gBA" x="144" y="228"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_qL4y4TXFEe2Sd_Hpmn5gBA"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#bdb751e9-3902-4553-92ab-833f74f5e3a1?fileId=bdb751e9-3902-4553-92ab-833f74f5e3a1$type=proc$name=Update%20variable?"/>
  <edges xmi:type="notation:Edge" xmi:id="_uHBLsDXFEe2Sd_Hpmn5gBA" type="4001" source="_r3eyADXFEe2Sd_Hpmn5gBA" target="_tcluoDXFEe2Sd_Hpmn5gBA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_uHBLsTXFEe2Sd_Hpmn5gBA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_uHBLsjXFEe2Sd_Hpmn5gBA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#b6e5db0a-3b6e-45dd-beb4-e848ffa1c59f?fileId=bdb751e9-3902-4553-92ab-833f74f5e3a1$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uHBLszXFEe2Sd_Hpmn5gBA" points="[-1, 20, 0, -80]$[-1, 100, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uHCZ0DXFEe2Sd_Hpmn5gBA" id="(0.4111111111111111,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uHCZ0TXFEe2Sd_Hpmn5gBA" id="(0.3389830508474576,0.0)"/>
  </edges>
</notation:Diagram>
]]></diagram>
</proc:process>