DROP SCHEMA INTEGRATED_FILES IF EXISTS CASCADE;
CREATE SCHEMA INTEGRATED_FILES;

CREATE TABLE INTEGRATED_FILES.BILLING (
BILLING_ID INTEGER NOT NULL,
BILLING_CREATION_DATE NUMERIC(8),
CUSTOMER_ID INTEGER,
BILLING_STATUS INTEGER,
BILLING_LINES_NUMBER_SENT INTEGER,
BILLING_LINES_NUMBER_LOG INTEGER,
CONSTRAINT PK_BILLING PRIMARY KEY (BILLING_ID));

CREATE TABLE INTEGRATED_FILES.BILLING_LINE(
BILLING_ID INTEGER NOT NULL,
BILLING_LINE INTEGER NOT NULL,
PRODUCT_ID INTEGER,
BILLING_QTY INTEGER,
CONSTRAINT PK_BILLING_LINE PRIMARY KEY (BILLING_ID,BILLING_LINE));

