<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="cdd96b1a-c808-43f2-b3cb-bf2bc638daed">
  <actionCode id="8af2ae41-26b3-46cb-8d79-239ff0569881" isBeginAction="false" name="Write Execution Report End" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.WriteTxtFileActionCodeI">
    <metaDataLink id="eaa8c1c9-06b5-4390-96fa-4f4a967d241f" name="Statistic_Report_Folder" target="resource.md#_ktIrYDN5Ee2HNZiLrCljlg?fileId=_iPyVsDA4Ee2gO4RlfKX5uw$type=md$name=Statistic_Report_Folder?"/>
    <parameter id="34536f44-ea73-4a1c-8bbe-2d225c5c3d22" name="TXT_WRITE_FILENAME" type="String" value="%x{$Statistic_Report_Folder/tech:path()}x%/Load Hotel Datamart_%x{md:formatDate(&quot;yyyyMMdd&quot;)}x%.html"/>
    <parameter id="afc66d60-5894-4479-8505-fdf3840c11c6" name="TXT_WRITE_APPEND" type="String" value="after"/>
    <code>&lt;tfoot> &#xD;
   &lt;tr>&#xD;
     &lt;th> Total for ${/CORE_SESSION_NAME}$ &lt;/th>  &#xD;
     &lt;th> ${/CORE_BEGIN_DATE}$ &lt;/th>&#xD;
     &lt;th style='text-align:right;bold;'> ${../Load_Hotel_Datamart/CORE_DURATION}$ &lt;/th>&#xD;
     &lt;th style='text-align:right;bold;'> %e(rhino){__ctx__.sumVariable(&quot;SQL_NB_ROWS&quot;,&quot;../Load_Hotel_Datamart&quot;)}e(rhino)%&lt;/th>&#xD;
     &lt;th style='text-align:right;bold;'> %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_INSERT&quot;,&quot;../Load_Hotel_Datamart&quot;)}e(rhino)%&lt;/th>&#xD;
     &lt;th style='text-align:right;bold;'> %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_UPDATE&quot;,&quot;../Load_Hotel_Datamart&quot;)}e(rhino)%&lt;/th>&#xD;
     &lt;th style='text-align:right;bold;'> %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_DELETE&quot;,&quot;../Load_Hotel_Datamart&quot;)}e(rhino)%&lt;/th>&#xD;
     &lt;th style='text-align:right;bold;'> %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_ERROR&quot;,&quot;../Load_Hotel_Datamart&quot;)}e(rhino)%&lt;/th>&#xD;
   &lt;/tr>&#xD;
 &lt;/tfoot>&#xD;
&lt;/table></code>
  </actionCode>
  <subProcess id="a358d207-f083-4488-9ec1-6f93022f8a24" generationCondition="" isBeginAction="false" name="Load_Hotel_Datamart" nbCycles="-1" toleratedError="false">
    <link id="396ba4b2-1c2e-462e-b227-12731408b571" executionType="OK" generationType="OK_KO" mandatory="1" targetId="8af2ae41-26b3-46cb-8d79-239ff0569881"/>
    <parameter id="cc0659e3-270f-47a5-bd49-10b7ea446ffc" name="resetAll" type="Boolean" value="true"/>
    <actionCode id="8947766b-6a5a-4ca0-9988-a81f0920b003" isBeginAction="false" name="Start Load" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="e54bdc55-abb1-4550-9bd1-03ff0eb6ed08" executionType="OK" generationType="OK_KO" mandatory="1" targetId="7a2c292a-7342-45a0-8eda-7c373b305b10"/>
      <link id="d50e3bf5-a719-4153-8311-9a2f4b6ba59e" executionType="OK" generationType="OK_KO" mandatory="1" targetId="a5c3f9be-ead5-46eb-933c-d9ff05bb30d9"/>
      <link id="b2dc6836-926f-4058-9716-8f5e0eb1f4d2" executionType="OK" generationType="OK_KO" mandatory="1" targetId="a8e315c0-8f20-4e3a-9359-35f2dd0db023"/>
      <link id="61f2973c-002c-4254-8495-7b9f7d06f29a" executionType="OK" generationType="OK_KO" mandatory="1" targetId="bdea742b-2c9e-409c-ba25-aa69ecd1bbe2"/>
      <link id="78cb1bfa-8cd8-4c5e-916a-26a12d6ef22a" executionType="OK" generationType="OK_KO" mandatory="1" targetId="14cf8754-48c4-42cd-bf9d-965b28947dcb"/>
    </actionCode>
    <actionCode id="523b36e5-169e-451d-b46a-327cdef53035" isBeginAction="false" name="End Load" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="8027e7a1-6459-4782-943d-a31695fe2a27" generationCondition="" executionType="OK" generationType="OK_KO" mandatory="1" targetId="144d255f-b005-4c66-adb5-6ed3f1dcb88b"/>
      <code></code>
    </actionCode>
    <actionCode id="49fb57c1-0bb6-4dbb-9eb1-97c43c26682d" isBeginAction="false" name="Init dim_discount" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JdbcActionCodeI">
      <link id="e4f30d3e-a15a-42bb-8851-8e68163c9a5f" executionType="OK" generationType="OK_KO" mandatory="1" targetId="8947766b-6a5a-4ca0-9988-a81f0920b003"/>
      <metaDataLink id="c35036d0-e4fa-4422-9787-0e8bef966f22" name="dim_discount" target="resource.md#_SPVJ0TA4Ee2gO4RlfKX5uw?fileId=_6v7gIDA3Ee2gO4RlfKX5uw$type=md$name=dim_discount?"/>
      <parameter id="a1c68c6e-bc82-4b0f-9a7a-1af4830a1c0e" name="SQL_ACTION_TYPE" type="String" value="DDL_DML"/>
      <parameter id="979a2c8d-ef20-4015-860f-435a6d4a3c47" name="SQL_ACTION_TYPE_STAT" type="String" value="INSERT"/>
      <code>INSERT INTO datamart.hotel_datamart.dim_discount (dis_range, dis_min, dis_max) VALUES ('No discount',NULL,NULL);</code>
    </actionCode>
    <actionCode id="e0c1a647-da4b-4672-a102-a7134ee68e56" isBeginAction="false" name="Init dim_geography" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JdbcActionCodeI">
      <link id="37ae72a6-fc52-43ec-aa81-6074bfdff7e1" executionType="OK" generationType="OK_KO" mandatory="1" targetId="8947766b-6a5a-4ca0-9988-a81f0920b003"/>
      <metaDataLink id="32cdc632-7fec-4dc7-973a-fdb7e37909a8" name="dim_geography" target="resource.md#_SK2ScTA4Ee2gO4RlfKX5uw?fileId=_6v7gIDA3Ee2gO4RlfKX5uw$type=md$name=dim_geography?"/>
      <parameter id="de5fed2e-ff59-4670-a246-9b75e3cc4579" name="SQL_ACTION_TYPE" type="String" value="DDL_DML"/>
      <parameter id="fa03c827-c8f2-4f4b-a797-0748d81dbffb" name="SQL_MULTI_QUERYS" type="Boolean" value="true"/>
      <parameter id="07e3852c-38c4-472c-b62d-aa25f81cc191" name="SQL_ACTION_TYPE_STAT" type="String" value="INSERT"/>
      <code>INSERT INTO datamart.hotel_datamart.dim_geography (geo_key_id, geo_zip_code, geo_city, geo_state_code, geo_state) VALUES (0, NULL, 'No Address', NULL, NULL);&#xD;
INSERT INTO datamart.hotel_datamart.dim_geography (geo_key_id, geo_zip_code, geo_city, geo_state_code, geo_state) VALUES (1, '?', 'Unknown Zip Code', '?', '?');</code>
    </actionCode>
    <actionCode id="4cb02450-1dc8-414e-838b-5a93e14c6b3b" generationCondition="" isBeginAction="false" name="Start" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="37fbb87f-5b19-4319-9e03-9023dbe0f52b" generationCondition="md:paramValue($this,'resetAll')=true()" executionType="OK" generationType="OK_KO" mandatory="1" targetId="2e06ba6d-1d34-4cf2-839e-4b9d993603d2"/>
      <link id="d436a5ec-ca88-48d8-8368-dbb88626822c" generationCondition="md:paramValue($this,'resetAll')=false()" executionType="OK" generationType="OK_KO" mandatory="1" targetId="8947766b-6a5a-4ca0-9988-a81f0920b003"/>
    </actionCode>
    <actionCode id="399b8bdc-6df0-4507-834f-2d25cb220488" generationCondition="" isBeginAction="false" name="Write Execution Report" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.WriteTxtFileActionCodeI">
      <metaDataLink id="d03177ad-0603-468f-b54c-260bd23b2d03" name="Statistic_Report_Folder" target="resource.md#_ktIrYDN5Ee2HNZiLrCljlg?fileId=_iPyVsDA4Ee2gO4RlfKX5uw$type=md$name=Statistic_Report_Folder?"/>
      <parameter id="2864c04e-5aba-4f5d-b69f-88bf2fe060ce" name="TXT_WRITE_FILENAME" type="String" value="%x{$Statistic_Report_Folder/tech:path()}x%/Load Hotel Datamart_%x{md:formatDate(&quot;yyyyMMdd&quot;)}x%.html"/>
      <code>&lt;h1> Execution result for ${/CORE_SESSION_NAME}$ &lt;/h1>&#xD;
&lt;br> &#xD;
&lt;table BORDER=&quot;3&quot;>&#xD;
 &lt;caption>Actions&lt;/caption>&#xD;
   &lt;tr>&#xD;
       &lt;th>Name&lt;/th>&#xD;
       &lt;th>Begin&lt;/th>&#xD;
       &lt;th>Duration&lt;/th>&#xD;
       &lt;th>Rows&lt;/th>&#xD;
       &lt;th>Insert&lt;/th>&#xD;
       &lt;th>Update&lt;/th>&#xD;
       &lt;th>Delete&lt;/th>&#xD;
       &lt;th>Reject&lt;/th>&#xD;
   &lt;/tr>&#xD;
  &#xD;
%x{md:patternList(&#xD;
../*[(@name != '') and (@name != 'resetAll') and (not(contains(upper-case(@name),'REJECT'))) and (not(contains(upper-case(@name),'REPORT')))]&#xD;
    [(not(contains(upper-case(@name),'CONSTRAINTS') &#xD;
          or contains(upper-case(@name),'INIT')) and (md:paramValue($this,'resetAll')=false())&#xD;
     ) or (md:paramValue($this,'resetAll')=true())],&#xD;
'&amp;lt;tr&amp;gt;&#xD;
 &amp;lt;td&amp;gt; {@name} &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td&amp;gt; ${../{@name}/CORE_BEGIN_DATE}$  &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td style=&amp;quot;text-align:right;&amp;quot;&amp;gt; ${../{@name}/CORE_DURATION}$ &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td style=&amp;quot;text-align:right;&amp;quot;&amp;gt; %e(rhino){__ctx__.sumVariable(&quot;SQL_NB_ROWS&quot;,&quot;../{@name}&quot;)}e(rhino)% &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td style=&amp;quot;text-align:right;&amp;quot;&amp;gt; %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_INSERT&quot;,&quot;../{@name}&quot;)}e(rhino)% &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td style=&amp;quot;text-align:right;&amp;quot;&amp;gt; %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_UPDATE&quot;,&quot;../{@name}&quot;)}e(rhino)%  &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td style=&amp;quot;text-align:right;&amp;quot;&amp;gt; %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_DELETE&quot;,&quot;../{@name}&quot;)}e(rhino)% &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;td style=&amp;quot;text-align:right;&amp;quot;&amp;gt; %e(rhino){__ctx__.sumVariable(&quot;SQL_STAT_ERROR&quot;,&quot;../{@name}&quot;)}e(rhino)% &amp;lt;/td&amp;gt; &#xD;
 &amp;lt;/tr&amp;gt;', &#xD;
'\n')}x%</code>
    </actionCode>
    <actionProcessRef id="a8e315c0-8f20-4e3a-9359-35f2dd0db023" isBeginAction="false" name="LoadDim_bedroom" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_PKDE0DBBEe2gO4RlfKX5uw?fileId=_PKDE0DBBEe2gO4RlfKX5uw$name=LoadDim_bedroom$type=map?">
      <link id="8e2bef4e-8f4e-47c9-a957-fcece997f4e0" executionType="OK" generationType="OK_KO" mandatory="1" targetId="3fd544f9-0526-4442-80f4-6058dfd7ac69"/>
    </actionProcessRef>
    <actionProcessRef id="ffbef6a2-3eec-4b57-9f41-18d96fa02daf" isBeginAction="false" name="LoadDim_customer" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_B9v6QDBPEe2gO4RlfKX5uw?fileId=_B9v6QDBPEe2gO4RlfKX5uw$name=LoadDim_customer$type=map?">
      <link id="381fed8e-b841-4280-99b6-20d5cf009a52" executionType="OK" generationType="OK_KO" mandatory="1" targetId="3fd544f9-0526-4442-80f4-6058dfd7ac69"/>
      <link id="a05bd405-2158-46c6-8986-62ce3a70471a" executionType="OK" generationType="OK_KO" mandatory="1" targetId="4feaa9d2-b394-4e09-a034-92609f8a1d1e"/>
    </actionProcessRef>
    <actionProcessRef id="bdea742b-2c9e-409c-ba25-aa69ecd1bbe2" isBeginAction="false" name="LoadDim_discount" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_ifP4kDA5Ee2gO4RlfKX5uw?fileId=_ifP4kDA5Ee2gO4RlfKX5uw$name=LoadDim_discount$type=map?">
      <link id="05f97f74-6564-4ffd-a197-e583c8c40eee" executionType="OK" generationType="OK_KO" mandatory="1" targetId="4feaa9d2-b394-4e09-a034-92609f8a1d1e"/>
    </actionProcessRef>
    <actionProcessRef id="7a2c292a-7342-45a0-8eda-7c373b305b10" isBeginAction="false" name="LoadDim_geography" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_GmG3YDBNEe2gO4RlfKX5uw?fileId=_GmG3YDBNEe2gO4RlfKX5uw$name=LoadDim_geography$type=map?">
      <link id="6d29aeb1-feb0-4910-a939-a09fbe1ebf2f" executionType="OK" generationType="OK_KO" mandatory="1" targetId="ffbef6a2-3eec-4b57-9f41-18d96fa02daf"/>
    </actionProcessRef>
    <actionProcessRef id="14cf8754-48c4-42cd-bf9d-965b28947dcb" isBeginAction="false" name="LoadDim_payment_type" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_GHIvUDBAEe2gO4RlfKX5uw?fileId=_GHIvUDBAEe2gO4RlfKX5uw$name=LoadDim_payment_type$type=map?">
      <link id="cdcb873e-db33-40c4-899f-ec133727db55" executionType="OK" generationType="OK_KO" mandatory="1" targetId="4feaa9d2-b394-4e09-a034-92609f8a1d1e"/>
    </actionProcessRef>
    <actionProcessRef id="a5c3f9be-ead5-46eb-933c-d9ff05bb30d9" isBeginAction="false" name="LoadDim_time" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_WapjoDK9Ee2kvaJkKfquyQ?fileId=_WapjoDK9Ee2kvaJkKfquyQ$name=LoadDim_time$type=map?">
      <link id="097c261c-6973-49d5-8846-ebbb2596b13a" executionType="OK" generationType="OK_KO" mandatory="1" targetId="3fd544f9-0526-4442-80f4-6058dfd7ac69"/>
      <link id="4da64f5d-2833-4368-b050-e680b6246c9b" executionType="OK" generationType="OK_KO" mandatory="1" targetId="4feaa9d2-b394-4e09-a034-92609f8a1d1e"/>
    </actionProcessRef>
    <actionProcessRef id="4feaa9d2-b394-4e09-a034-92609f8a1d1e" isBeginAction="false" name="LoadFact_billing" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_4gHDQDNQEe2HNZiLrCljlg?fileId=_4gHDQDNQEe2HNZiLrCljlg$name=LoadFact_billing$type=map?">
      <link id="e1d9800b-44ea-4ddf-968f-18fbeffa4d53" executionType="OK" generationType="OK_KO" mandatory="1" targetId="523b36e5-169e-451d-b46a-327cdef53035"/>
    </actionProcessRef>
    <actionProcessRef id="3fd544f9-0526-4442-80f4-6058dfd7ac69" isBeginAction="false" name="LoadFact_booking" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_Np_FoDLFEe2I8opIze4gbg?fileId=_Np_FoDLFEe2I8opIze4gbg$name=LoadFact_booking$type=map?">
      <link id="95f068ea-a297-4323-8aca-077aa2adaf99" executionType="OK" generationType="OK_KO" mandatory="1" targetId="523b36e5-169e-451d-b46a-327cdef53035"/>
    </actionProcessRef>
    <actionProcessRef id="2e06ba6d-1d34-4cf2-839e-4b9d993603d2" isBeginAction="false" name="Drop constraints" nbCycles="-1" toleratedError="false" targetName="resource.proc#_sknoQ6x2Ed6xTOAeaNjskA?fileId=_sknoQ6x2Ed6xTOAeaNjskA$type=proc$name=AUTOMATION%20Rdbms%20Operations.tp?">
      <link id="e7fee242-7358-4f45-aa88-65c17df6d982" executionType="OK" generationType="OK_KO" mandatory="1" targetId="49fb57c1-0bb6-4dbb-9eb1-97c43c26682d"/>
      <link id="5f9c7ad8-c45c-48ef-8f0f-3f2a89e9b2a2" executionType="OK" generationType="OK_KO" mandatory="1" targetId="e0c1a647-da4b-4672-a102-a7134ee68e56"/>
      <metaDataLink id="cbcdf034-4406-4ecb-8b51-d232979119c0" name="SOURCE" target="resource.md#_7CX7ADA3Ee2gO4RlfKX5uw?fileId=_6v7gIDA3Ee2gO4RlfKX5uw$type=md$name=datamart.hotel_datamart?"/>
      <parameter id="94cff748-d740-447d-abc5-d1062bb46478" name="dropFk" type="Boolean" value="true"/>
      <parameter id="fe2ce2d0-df34-4891-ae06-b2de9b3a4298" name="truncateTables" type="Boolean" value="true"/>
    </actionProcessRef>
    <actionProcessRef id="144d255f-b005-4c66-adb5-6ed3f1dcb88b" generationCondition="md:paramValue($this,'resetAll')=true()" isBeginAction="false" name="Recreate constraints" nbCycles="-1" toleratedError="false" targetName="resource.proc#_sknoQ6x2Ed6xTOAeaNjskA?fileId=_sknoQ6x2Ed6xTOAeaNjskA$type=proc$name=AUTOMATION%20Rdbms%20Operations.tp?">
      <link id="324f928c-a556-4606-913c-3682194b9870" executionType="OK" generationType="OK_KO" mandatory="1" targetId="399b8bdc-6df0-4507-834f-2d25cb220488"/>
      <parameter id="7a40e0f4-2b3d-46c3-9c62-2c11223f9583" name="createFk" type="Boolean" value="true"/>
    </actionProcessRef>
  </subProcess>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed?">
  <notation:Diagram xmi:id="_pJARMDNiEe2HNZiLrCljlg" type="Proc" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_vtiVMDNiEe2HNZiLrCljlg" type="2004">
      <children xmi:type="notation:Node" xmi:id="_vtlYgDNiEe2HNZiLrCljlg" type="5004"/>
      <children xmi:type="notation:Node" xmi:id="_vtlYgTNiEe2HNZiLrCljlg" type="7005">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_vtlYgjNiEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_vtlYgzNiEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_vtlYhDNiEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_vtlYhTNiEe2HNZiLrCljlg" type="7006">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_vtlYhjNiEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_vtlYhzNiEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_vtlYiDNiEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_vtiVMTNiEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="_vtiVMjNiEe2HNZiLrCljlg"/>
      <element xmi:type="proc:SubActionProcess" href="resource.proc#a358d207-f083-4488-9ec1-6f93022f8a24?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Load_Hotel_Datamart?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vtiVMzNiEe2HNZiLrCljlg" x="48" y="24"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_JZKVIDN_Ee2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_JZMKUDN_Ee2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_JZMKUTN_Ee2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_JZMKUjN_Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_JZMKUzN_Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_JZMKVDN_Ee2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_JZMKVTN_Ee2HNZiLrCljlg" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_JZMKVjN_Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_JZMKVzN_Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_JZMKWDN_Ee2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_JZKVITN_Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#8af2ae41-26b3-46cb-8d79-239ff0569881?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Write%20Execution%20Report%20End?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_JZKVIjN_Ee2HNZiLrCljlg" x="12" y="144"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_pJARMTNiEe2HNZiLrCljlg"/>
    <element xmi:type="proc:ActionProcess" href="resource.proc#cdd96b1a-c808-43f2-b3cb-bf2bc638daed?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadAllDatamart?"/>
    <edges xmi:type="notation:Edge" xmi:id="_Qd9NkDN_Ee2HNZiLrCljlg" type="4001" source="_vtiVMDNiEe2HNZiLrCljlg" target="_JZKVIDN_Ee2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_Qd9NkTN_Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Qd9NkjN_Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#396ba4b2-1c2e-462e-b227-12731408b571?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Qd9NkzN_Ee2HNZiLrCljlg" points="[0, 20, 0, -72]$[-90, 80, -90, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qd90oDN_Ee2HNZiLrCljlg" id="(0.4329268292682927,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qd90oTN_Ee2HNZiLrCljlg" id="(0.17833333333333334,0.15789473684210525)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_0K0_4DNiEe2HNZiLrCljlg" type="Proc" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_7vo1IDNiEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_7vwJ4DNiEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_7vwJ4TNiEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_7vwJ4jNiEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_7vwJ4zNiEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_7vwJ5DNiEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_7vwJ5TNiEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_7vwJ5jNiEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_7vwJ5zNiEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_7vwJ6DNiEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_7vo1ITNiEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#a8e315c0-8f20-4e3a-9359-35f2dd0db023?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadDim_bedroom?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7vo1IjNiEe2HNZiLrCljlg" x="24" y="-192"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Mj0kADNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_Mj74wDNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_Mj74wTNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_Mj74wjNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_Mj74wzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_Mj74xDNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_Mj74xTNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_Mj74xjNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_Mj74xzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_Mj74yDNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_Mj0kATNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#ffbef6a2-3eec-4b57-9f41-18d96fa02daf?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadDim_customer?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Mj0kAjNjEe2HNZiLrCljlg" x="180" y="-96"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_OTXPADNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_OTejwDNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_OTfK0DNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_OTfK0TNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_OTfK0jNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_OTfK0zNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_OTfx4DNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_OTfx4TNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_OTfx4jNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_OTfx4zNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_OTXPATNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#bdea742b-2c9e-409c-ba25-aa69ecd1bbe2?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadDim_discount?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OTXPAjNjEe2HNZiLrCljlg" x="492" y="-192"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_OmRj8DNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_OmZfwDNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_OmZfwTNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_OmZfwjNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_OmZfwzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_OmZfxDNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_OmZfxTNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_OmZfxjNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_OmZfxzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_OmZfyDNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_OmRj8TNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#7a2c292a-7342-45a0-8eda-7c373b305b10?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadDim_geography?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OmRj8jNjEe2HNZiLrCljlg" x="240" y="-192"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_O3X7ADNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_O3gd4DNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_O3hE8DNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_O3hE8TNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_O3hE8jNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_O3hE8zNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_O3hE9DNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_O3hE9TNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_O3hE9jNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_O3hE9zNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_O3X7ATNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#14cf8754-48c4-42cd-bf9d-965b28947dcb?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadDim_payment_type?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_O3X7AjNjEe2HNZiLrCljlg" x="696" y="-192"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_PwXYgDNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_PwiXoDNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_PwiXoTNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_PwiXojNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_PwiXozNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_PwiXpDNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_PwiXpTNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_PwiXpjNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_PwiXpzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_PwiXqDNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_PwXYgTNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#a5c3f9be-ead5-46eb-933c-d9ff05bb30d9?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadDim_time?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PwXYgjNjEe2HNZiLrCljlg" x="396" y="-96"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_SD6vgDNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_SECEQDNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_SECEQTNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_SECEQjNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_SECEQzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_SECERDNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_SECERTNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_SECERjNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_SECERzNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_SECESDNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_SD6vgTNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#4feaa9d2-b394-4e09-a034-92609f8a1d1e?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadFact_billing?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SD6vgjNjEe2HNZiLrCljlg" x="492" y="12"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_SXrZADNjEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_SXyGsDNjEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_SXyGsTNjEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_SXyGsjNjEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_SXyGszNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_SXyGtDNjEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_SXzU0DNjEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_SXzU0TNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_SXzU0jNjEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_SXzU0zNjEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_SXrZATNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#3fd544f9-0526-4442-80f4-6058dfd7ac69?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=LoadFact_booking?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SXrZAjNjEe2HNZiLrCljlg" x="180" y="12"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Z6u5wDNuEe2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_Z61AYDNuEe2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_Z61AYTNuEe2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_Z61AYjNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_Z61AYzNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_Z61AZDNuEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_Z61ncDNuEe2HNZiLrCljlg" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_Z61ncTNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_Z61ncjNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_Z61nczNuEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_Z6u5wTNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#8947766b-6a5a-4ca0-9988-a81f0920b003?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Start%20Load?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Z6u5wjNuEe2HNZiLrCljlg" x="396" y="-300"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_qB5KkDNuEe2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_qB_RMDNuEe2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_qB_RMTNuEe2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_qB_RMjNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_qB_RMzNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_qB_RNDNuEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_qB_RNTNuEe2HNZiLrCljlg" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_qB_RNjNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_qB_RNzNuEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_qB_RODNuEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_qB5KkTNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#523b36e5-169e-451d-b46a-327cdef53035?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=End%20Load?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qB5KkjNuEe2HNZiLrCljlg" x="360" y="108"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_II8dsDNvEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_IJFAkDNvEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_IJFAkTNvEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_IJFAkjNvEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_IJFAkzNvEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_IJFAlDNvEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_IJFAlTNvEe2HNZiLrCljlg" type="7004">
        <children xmi:type="notation:Node" xmi:id="_Em3WsDNyEe2HNZiLrCljlg" type="3004">
          <element xmi:type="proc:MetaDataLink" href="resource.proc#cbcdf034-4406-4ecb-8b51-d232979119c0?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
          <layoutConstraint xmi:type="notation:Location" xmi:id="_Em3WsTNyEe2HNZiLrCljlg"/>
        </children>
        <styles xmi:type="notation:DrawerStyle" xmi:id="_IJFAljNvEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_IJFAlzNvEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_IJFAmDNvEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_II8dsTNvEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#2e06ba6d-1d34-4cf2-839e-4b9d993603d2?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Drop%20constraints?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_II8dsjNvEe2HNZiLrCljlg" x="372" y="-576"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_fRwE8DNyEe2HNZiLrCljlg" type="2003">
      <children xmi:type="notation:Node" xmi:id="_fR2yoDNyEe2HNZiLrCljlg" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="_fR2yoTNyEe2HNZiLrCljlg" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_fR2yojNyEe2HNZiLrCljlg" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_fR2yozNyEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_fR2ypDNyEe2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_fR4AwDNyEe2HNZiLrCljlg" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_fR4AwTNyEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_fR4AwjNyEe2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_fR4AwzNyEe2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_fRwE8TNyEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="resource.proc#144d255f-b005-4c66-adb5-6ed3f1dcb88b?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Recreate%20constraints?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fRwE8jNyEe2HNZiLrCljlg" x="336" y="216"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_cvs3kDN1Ee2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_cvwh8DN1Ee2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_cvxJADN1Ee2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_cvxJATN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_cvxJAjN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_cvxJAzN1Ee2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_cvxJBDN1Ee2HNZiLrCljlg" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_cvxJBTN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_cvxJBjN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_cvxJBzN1Ee2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_cvs3kTN1Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#49fb57c1-0bb6-4dbb-9eb1-97c43c26682d?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Init%20dim_discount?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cvs3kjN1Ee2HNZiLrCljlg" x="48" y="-468"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_td3eADN1Ee2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_td89kDN1Ee2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_td9koDN1Ee2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_td9koTN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_td9kojN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_td9kozN1Ee2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_td9kpDN1Ee2HNZiLrCljlg" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_td9kpTN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_td9kpjN1Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_td9kpzN1Ee2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_td3eATN1Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#e0c1a647-da4b-4672-a102-a7134ee68e56?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Init%20dim_geography?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_td3eAjN1Ee2HNZiLrCljlg" x="324" y="-468"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_wcrbsDN5Ee2HNZiLrCljlg" type="2005">
      <children xmi:type="notation:Node" xmi:id="_wcvtIDN5Ee2HNZiLrCljlg" type="5005"/>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_wcrbsTN5Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Parameter" href="resource.proc#cc0659e3-270f-47a5-bd49-10b7ea446ffc?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=resetAll?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wcrbsjN5Ee2HNZiLrCljlg" x="888" y="12"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_7LiLEDN5Ee2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_7LqG4DN5Ee2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_7LqG4TN5Ee2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_7LqG4jN5Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_7LqG4zN5Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_7LqG5DN5Ee2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_7LtKMDN5Ee2HNZiLrCljlg" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_7LtKMTN5Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_7LtKMjN5Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_7LtKMzN5Ee2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_7LiLETN5Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#4cb02450-1dc8-414e-838b-5a93e14c6b3b?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Start?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7LiLEjN5Ee2HNZiLrCljlg" x="552" y="-684"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_PrG7sDN8Ee2HNZiLrCljlg" type="2001">
      <children xmi:type="notation:Node" xmi:id="_PrPekDN8Ee2HNZiLrCljlg" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="_PrPekTN8Ee2HNZiLrCljlg" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="_PrPekjN8Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_PrPekzN8Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_PrPelDN8Ee2HNZiLrCljlg"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_PrQFoDN8Ee2HNZiLrCljlg" type="7002">
        <children xmi:type="notation:Node" xmi:id="_gGtygDN8Ee2HNZiLrCljlg" type="3002">
          <element xmi:type="proc:MetaDataLink" href="resource.proc#d03177ad-0603-468f-b54c-260bd23b2d03?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
          <layoutConstraint xmi:type="notation:Location" xmi:id="_gGtygTN8Ee2HNZiLrCljlg"/>
        </children>
        <styles xmi:type="notation:DrawerStyle" xmi:id="_PrQFoTN8Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="_PrQFojN8Ee2HNZiLrCljlg"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="_PrQFozN8Ee2HNZiLrCljlg"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="_PrG7sTN8Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="resource.proc#399b8bdc-6df0-4507-834f-2d25cb220488?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Write%20Execution%20Report?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PrG7sjN8Ee2HNZiLrCljlg" x="108" y="336"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_0K0_4TNiEe2HNZiLrCljlg"/>
    <element xmi:type="proc:SubActionProcess" href="resource.proc#a358d207-f083-4488-9ec1-6f93022f8a24?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc$name=Load_Hotel_Datamart?"/>
    <edges xmi:type="notation:Edge" xmi:id="_zDHUcDNjEe2HNZiLrCljlg" type="4001" source="_OmRj8DNjEe2HNZiLrCljlg" target="_Mj0kADNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_zDHUcTNjEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_zDHUcjNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#6d29aeb1-feb0-4910-a939-a09fbe1ebf2f?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zDHUczNjEe2HNZiLrCljlg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zDH7gDNjEe2HNZiLrCljlg" id="(0.11320754716981132,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zDH7gTNjEe2HNZiLrCljlg" id="(0.49673202614379086,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_2jFbQDNjEe2HNZiLrCljlg" type="4001" source="_Mj0kADNjEe2HNZiLrCljlg" target="_SXrZADNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_2jFbQTNjEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_2jFbQjNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#381fed8e-b841-4280-99b6-20d5cf009a52?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2jFbQzNjEe2HNZiLrCljlg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2jGCUDNjEe2HNZiLrCljlg" id="(0.49673202614379086,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCntcTNqEe2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_37hN0DNjEe2HNZiLrCljlg" type="4001" source="_PwXYgDNjEe2HNZiLrCljlg" target="_SXrZADNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_37hN0TNjEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_37hN0jNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#097c261c-6973-49d5-8846-ebbb2596b13a?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_37hN0zNjEe2HNZiLrCljlg" points="[0, 0, 142, -60]$[-142, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_37h04DNjEe2HNZiLrCljlg" id="(0.3333333333333333,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCnGYTNqEe2HNZiLrCljlg" id="(0.7465753424657534,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_5kldYDNjEe2HNZiLrCljlg" type="4001" source="_Mj0kADNjEe2HNZiLrCljlg" target="_SD6vgDNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_5kldYTNjEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_5kldYjNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#a05bd405-2158-46c6-8986-62ce3a70471a?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5kldYzNjEe2HNZiLrCljlg" points="[0, 0, -222, -60]$[222, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5kmEcDNjEe2HNZiLrCljlg" id="(0.7450980392156863,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCntcjNqEe2HNZiLrCljlg" id="(0.16417910447761194,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_7L8cwDNjEe2HNZiLrCljlg" type="4001" source="_PwXYgDNjEe2HNZiLrCljlg" target="_SD6vgDNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_7L8cwTNjEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_7L8cwjNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#4da64f5d-2833-4368-b050-e680b6246c9b?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7L8cwzNjEe2HNZiLrCljlg" points="[0, 0, -63, -60]$[63, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7L-R8DNjEe2HNZiLrCljlg" id="(0.6666666666666666,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCnGYDNqEe2HNZiLrCljlg" id="(0.3283582089552239,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_80tKUDNjEe2HNZiLrCljlg" type="4001" source="_OTXPADNjEe2HNZiLrCljlg" target="_SD6vgDNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_80tKUTNjEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_80tKUjNjEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#05f97f74-6564-4ffd-a197-e583c8c40eee?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_80tKUzNjEe2HNZiLrCljlg" points="[0, 0, 0, -161]$[0, 161, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_80txYDNjEe2HNZiLrCljlg" id="(0.4965986394557823,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCnGYjNqEe2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_eUWw8DNkEe2HNZiLrCljlg" type="4001" source="_7vo1IDNiEe2HNZiLrCljlg" target="_SXrZADNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_eUWw8TNkEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_eUWw8jNkEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#8e2bef4e-8f4e-47c9-a957-fcece997f4e0?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eUWw8zNkEe2HNZiLrCljlg" points="[0, 0, -83, -161]$[0, 100, -83, -61]$[83, 161, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_eUXYADNkEe2HNZiLrCljlg" id="(0.7181208053691275,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCntczNqEe2HNZiLrCljlg" id="(0.2465753424657534,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_f46T8DNkEe2HNZiLrCljlg" type="4001" source="_O3X7ADNjEe2HNZiLrCljlg" target="_SD6vgDNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_f46T8TNkEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_f46T8jNkEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#cdcb873e-db33-40c4-899f-ec133727db55?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f46T8zNkEe2HNZiLrCljlg" points="[0, 0, 190, -161]$[-190, 161, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_f48JIDNkEe2HNZiLrCljlg" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tCntcDNqEe2HNZiLrCljlg" id="(0.746268656716418,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_kJWp4DNuEe2HNZiLrCljlg" type="4001" source="_Z6u5wDNuEe2HNZiLrCljlg" target="_OmRj8DNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_kJWp4TNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_kJWp4jNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#e54bdc55-abb1-4550-9bd1-03ff0eb6ed08?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kJWp4zNuEe2HNZiLrCljlg" points="[0, 0, 109, -60]$[-109, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kJXQ8DNuEe2HNZiLrCljlg" id="(0.33663366336633666,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kJXQ8TNuEe2HNZiLrCljlg" id="(0.4968553459119497,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_lpe_4DNuEe2HNZiLrCljlg" type="4001" source="_Z6u5wDNuEe2HNZiLrCljlg" target="_PwXYgDNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_lpe_4TNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_lpe_4jNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#d50e3bf5-a719-4153-8311-9a2f4b6ba59e?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lpe_4zNuEe2HNZiLrCljlg" points="[0, 0, 0, -161]$[0, 161, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lpfm8DNuEe2HNZiLrCljlg" id="(0.5148514851485149,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lpfm8TNuEe2HNZiLrCljlg" id="(0.4146341463414634,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_molFYDNuEe2HNZiLrCljlg" type="4001" source="_Z6u5wDNuEe2HNZiLrCljlg" target="_7vo1IDNiEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_molFYTNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_molFYjNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#b2dc6836-926f-4058-9716-8f5e0eb1f4d2?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_molFYzNuEe2HNZiLrCljlg" points="[0, 0, 306, -60]$[-306, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_molscDNuEe2HNZiLrCljlg" id="(0.16831683168316833,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_molscTNuEe2HNZiLrCljlg" id="(0.4966442953020134,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_nfQOsDNuEe2HNZiLrCljlg" type="4001" source="_Z6u5wDNuEe2HNZiLrCljlg" target="_OTXPADNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_nfQOsTNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_nfQOsjNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#61f2973c-002c-4254-8495-7b9f7d06f29a?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nfQOszNuEe2HNZiLrCljlg" points="[0, 0, -101, -60]$[101, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nfRc0DNuEe2HNZiLrCljlg" id="(0.6732673267326733,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nfRc0TNuEe2HNZiLrCljlg" id="(0.4965986394557823,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_oGqM8DNuEe2HNZiLrCljlg" type="4001" source="_Z6u5wDNuEe2HNZiLrCljlg" target="_O3X7ADNjEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_oGqM8TNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_oGqM8jNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#78cb1bfa-8cd8-4c5e-916a-26a12d6ef22a?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oGqM8zNuEe2HNZiLrCljlg" points="[0, 0, -308, -60]$[308, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oGq0ADNuEe2HNZiLrCljlg" id="(0.8316831683168316,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_oGq0ATNuEe2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_zJ538DNuEe2HNZiLrCljlg" type="4001" source="_SXrZADNjEe2HNZiLrCljlg" target="_qB5KkDNuEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_zJ538TNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_zJ538jNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#95f068ea-a297-4323-8aca-077aa2adaf99?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zJ538zNuEe2HNZiLrCljlg" points="[0, 0, -137, -60]$[137, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zJ6fADNuEe2HNZiLrCljlg" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zJ6fATNuEe2HNZiLrCljlg" id="(0.32978723404255317,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_z52HIDNuEe2HNZiLrCljlg" type="4001" source="_SD6vgDNjEe2HNZiLrCljlg" target="_qB5KkDNuEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_z52HITNuEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_z52HIjNuEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#e1d9800b-44ea-4ddf-968f-18fbeffa4d53?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z52HIzNuEe2HNZiLrCljlg" points="[0, 0, 137, -60]$[-137, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_z52uMDNuEe2HNZiLrCljlg" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0uTC4DNuEe2HNZiLrCljlg" id="(0.6595744680851063,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_nPR8MDNyEe2HNZiLrCljlg" type="4001" source="_qB5KkDNuEe2HNZiLrCljlg" target="_fRwE8DNyEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_nPR8MTNyEe2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_nPR8MjNyEe2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#8027e7a1-6459-4782-943d-a31695fe2a27?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nPR8MzNyEe2HNZiLrCljlg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nPSjQDNyEe2HNZiLrCljlg" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nPSjQTNyEe2HNZiLrCljlg" id="(0.4968944099378882,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_LSiAoDN2Ee2HNZiLrCljlg" type="4001" source="_II8dsDNvEe2HNZiLrCljlg" target="_cvs3kDN1Ee2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_LSiAoTN2Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_LSiAojN2Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#e7fee242-7358-4f45-aa88-65c17df6d982?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LSiAozN2Ee2HNZiLrCljlg" points="[0, 0, 244, -60]$[-244, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LSjOwDN2Ee2HNZiLrCljlg" id="(0.25,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LSjOwTN2Ee2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_L2Y7oDN2Ee2HNZiLrCljlg" type="4001" source="_II8dsDNvEe2HNZiLrCljlg" target="_td3eADN1Ee2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_L2Y7oTN2Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_L2Y7ojN2Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#5f9c7ad8-c45c-48ef-8f0f-3f2a89e9b2a2?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L2Y7ozN2Ee2HNZiLrCljlg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_L2ZisDN2Ee2HNZiLrCljlg" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_L2ZisTN2Ee2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_Mbfz0DN2Ee2HNZiLrCljlg" type="4001" source="_cvs3kDN1Ee2HNZiLrCljlg" target="_Z6u5wDNuEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_Mbfz0TN2Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Mbfz0jN2Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#e4f30d3e-a15a-42bb-8851-8e68163c9a5f?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Mbfz0zN2Ee2HNZiLrCljlg" points="[0, 0, -260, -76]$[260, 76, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MbhB8DN2Ee2HNZiLrCljlg" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MbhB8TN2Ee2HNZiLrCljlg" id="(0.24752475247524752,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_M_IsYDN2Ee2HNZiLrCljlg" type="4001" source="_td3eADN1Ee2HNZiLrCljlg" target="_Z6u5wDNuEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_M_IsYTN2Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_M_IsYjN2Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#37ae72a6-fc52-43ec-aa81-6074bfdff7e1?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_M_IsYzN2Ee2HNZiLrCljlg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_M_JTcDN2Ee2HNZiLrCljlg" id="(0.5321100917431193,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_M_JTcTN2Ee2HNZiLrCljlg" id="(0.49504950495049505,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="__vJgMDN5Ee2HNZiLrCljlg" type="4001" source="_7LiLEDN5Ee2HNZiLrCljlg" target="_II8dsDNvEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="__vKHQDN5Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="__vKHQTN5Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#37fbb87f-5b19-4319-9e03-9023dbe0f52b?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__vKHQjN5Ee2HNZiLrCljlg" points="[0, 0, 133, -60]$[-133, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__vKuUDN5Ee2HNZiLrCljlg" id="(0.2375,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__vKuUTN5Ee2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_X1vFsDN6Ee2HNZiLrCljlg" type="4001" source="_7LiLEDN5Ee2HNZiLrCljlg" target="_Z6u5wDNuEe2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_X1vFsTN6Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_X1vFsjN6Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#d436a5ec-ca88-48d8-8368-dbb88626822c?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_X1vFszN6Ee2HNZiLrCljlg" points="[0, 0, 121, -345]$[0, 284, 121, -61]$[-121, 345, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X1vswDN6Ee2HNZiLrCljlg" id="(0.4875,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_X1vswTN6Ee2HNZiLrCljlg" id="(0.7425742574257426,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="_1bTKcDN8Ee2HNZiLrCljlg" type="4001" source="_fRwE8DNyEe2HNZiLrCljlg" target="_PrG7sDN8Ee2HNZiLrCljlg">
      <styles xmi:type="notation:RoutingStyle" xmi:id="_1bTKcTN8Ee2HNZiLrCljlg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_1bTKcjN8Ee2HNZiLrCljlg" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="resource.proc#324f928c-a556-4606-913c-3682194b9870?fileId=cdd96b1a-c808-43f2-b3cb-bf2bc638daed$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1bTKczN8Ee2HNZiLrCljlg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1bTxgDN8Ee2HNZiLrCljlg" id="(0.4968944099378882,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2HLZADN8Ee2HNZiLrCljlg" id="(0.5,0.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
]]></diagram>
</proc:process>