<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_vu1hIYCREeaWqIy4qrYByg" name="Billing replication">
  <actionProcessRef id="_58zJ8ICREeaWqIy4qrYByg" isBeginAction="false" name="REPLICATOR Rdbms.tp" nbCycles="-1" toleratedError="false" targetName="../../global/templates.generic/Replication/REPLICATOR%20Rdbms.tp.proc#_zZDewaLZEd6qz86y5ipz-A?fileId=_zZDewaLZEd6qz86y5ipz-A$type=proc$name=REPLICATOR%20Rdbms.tp?">
    <metaDataLink id="_7nw28ICREeaWqIy4qrYByg" name="SOURCE" target="../Metadata/HSQL_Datamart.md#_8blbUH72Eea6zsl9X76vCw?fileId=_9gfDUH71Eea6zsl9X76vCw$type=md$name=ACTV_GEN?"/>
    <metaDataLink id="_74_w4ICREeaWqIy4qrYByg" name="TARGET" target="../Metadata/HSQL_Datamart.md#_ALbxMH73Eea6zsl9X76vCw?fileId=_9gfDUH71Eea6zsl9X76vCw$type=md$name=DUPL_GEN?"/>
    <parameter id="_-DEbwICREeaWqIy4qrYByg" name="dropFk" type="String" value="true"/>
    <parameter id="_-ILlQICREeaWqIy4qrYByg" name="dropPk" type="String" value="true"/>
    <parameter id="_-NXAMICREeaWqIy4qrYByg" name="createTables" type="String" value="true"/>
    <parameter id="_-UOdMICREeaWqIy4qrYByg" name="dropTables" type="String" value="true"/>
    <parameter id="_-mi8QICREeaWqIy4qrYByg" name="loadData" type="String" value="true"/>
    <parameter id="_-yqssICREeaWqIy4qrYByg" name="createPk" type="String" value="true"/>
    <parameter id="_-5_csICREeaWqIy4qrYByg" name="createFk" type="String" value="true"/>
  </actionProcessRef>
</proc:process>