DROP SCHEMA INTEGRATED_FILES IF EXISTS CASCADE;
CREATE SCHEMA INTEGRATED_FILES;
CREATE TABLE  INTEGRATED_FILES.ORDER (
ORDER_REF          VARCHAR(50) NOT NULL,
COMPANY              VARCHAR(100) NOT NULL,
ORDER_LINE_NUMBER  INTEGER,
ORDER_DATE         CHAR(8),
TOTAL_PRICE          DECIMAL(12,2),
COMPUTED_TOTAL_PRICE DECIMAL(12,2),
COMPUTED_LINE_NUMBER INTEGER,
CREATION_DATE        TIMESTAMP,
UPDATE_DATE          TIMESTAMP,
CONSTRAINT           PK_ORDER PRIMARY KEY (ORDER_REF,COMPANY));
CREATE TABLE  INTEGRATED_FILES.ORDER_BODY (
ORDER_REF          VARCHAR(50) NOT NULL,
COMPANY              VARCHAR(100) NOT NULL,
PRODUCT_ID           INTEGER NOT NULL,
QTY                  INTEGER,
UNIT_PRICE           DECIMAL(10,2),
CONSTRAINT           PK_ORDER_BODY PRIMARY KEY (ORDER_REF,COMPANY,PRODUCT_ID));