DROP SCHEMA WEB_SERVICE IF EXISTS CASCADE;
CREATE SCHEMA WEB_SERVICE;
CREATE TABLE WEB_SERVICE.GEOCODE_CITY
(ZIPCODE     INTEGER,
 STATE_CODE  CHAR(2),
 CITY        VARCHAR(50),
 LAT         DECIMAL(8,6),
 LON         DECIMAL(10,6),
 CONSTRAINT   PK_GEOCODE_CITY PRIMARY KEY (ZIPCODE,STATE_CODE,CITY)
 );
CREATE TABLE WEB_SERVICE.LOG_GEOCODER
(	
	SESSION_ID VARCHAR(100) NOT NULL,
	ADR_ID INTEGER NOT NULL,
	ADR_DESC VARCHAR(1000) ,
	FAULT_ACTOR VARCHAR(1000) ,
	FAULT_CODE VARCHAR(1000) ,
	FAULT_STRING VARCHAR(1000) ,
	EXEC_DATE TIMESTAMP 
	, CONSTRAINT PK_LOG_GEOCODER PRIMARY KEY (SESSION_ID,ADR_ID))
 