DROP SCHEMA PARAM IF EXISTS CASCADE;
CREATE SCHEMA PARAM;
CREATE TABLE PARAM.LST_PARAM (
ID_PARAM INTEGER,
PROCESS_INCLUSION VARCHAR(500),
PROCESS_EXCLUSION VARCHAR(500),
CONFIG VARCHAR(20),
PARAM_NAME VARCHAR(100),
PARAM_VALUE VARCHAR(100),
CONSTRAINT PK_LST_PARAM PRIMARY KEY (ID_PARAM));
INSERT INTO PARAM.LST_PARAM VALUES (1,'ALL',NULL,'ALL','SLEEP_PERIOD','2');
INSERT INTO PARAM.LST_PARAM VALUES (2,'P1',NULL,'Default','DIRECTION_DECISION','LEFT');
INSERT INTO PARAM.LST_PARAM VALUES (3,'P2',NULL,'Default','DIRECTION_DECISION','RIGHT');
INSERT INTO PARAM.LST_PARAM VALUES (5,'ALL','P2','Default','CONDITIONAL_ACTION','TRUE');
INSERT INTO PARAM.LST_PARAM VALUES (7,'P1,P2',NULL,'ALL','ITERATION','2');
INSERT INTO PARAM.LST_PARAM VALUES (8,'P3',NULL,'ALL','ITERATION','3');