<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_4hSaQcAnEeq6L8zfnBksuA">
  <actionProcessRef id="_4hSaQsAnEeq6L8zfnBksuA" isBeginAction="false" name="get Errors" nbCycles="-1" toleratedError="false" targetName="../../../../Components/Control%20Management/TOOL_getError.proc#_mowwwYF-Eean7JATlUQCiw?fileId=_mowwwYF-Eean7JATlUQCiw$type=proc$name=TOOL_getError?">
    <metaDataLink id="31c00411-9ab7-4bdf-b089-29d61904b701" name="TARGET_SCHEMA" target="HSQL_Datamart.md#_x-XGUcUZEeqlFMxK4WGtuA?fileId=_x-V3YMUZEeqlFMxK4WGtuA$type=md$name=PARAM?"/>
  </actionProcessRef>
  <actionProcessRef id="_4hSaRMAnEeq6L8zfnBksuA" isBeginAction="false" name="Init parameters" nbCycles="-1" toleratedError="false" targetName="Init%20parameters.proc#_4hSaQMAnEeq6L8zfnBksuA?fileId=_4hSaQMAnEeq6L8zfnBksuA$type=proc$name=Init%20parameters?">
    <link id="_4hSaRcAnEeq6L8zfnBksuA" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_4hSaR8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Process%20body?"/>
    <link id="_4hSaRsAnEeq6L8zfnBksuA" executionType="KO" generationType="OK_KO" mandatory="0" targetId="_4hSaQsAnEeq6L8zfnBksuA"/>
  </actionProcessRef>
  <subProcess id="_4hSaR8AnEeq6L8zfnBksuA" isBeginAction="false" name="Process body" nbCycles="-1" toleratedError="false">
    <link id="_4hSaSMAnEeq6L8zfnBksuA" executionType="KO" generationType="OK_KO" mandatory="0" targetId="_4hSaQsAnEeq6L8zfnBksuA"/>
    <actionCode id="_4hSaScAnEeq6L8zfnBksuA" isBeginAction="true" name="Loop" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="_4hSaSsAnEeq6L8zfnBksuA" executionCondition="${Loop/CORE_NB_EXECUTIONS}$ > ${~/P_GEN_ITERATION}$&#xD;&#xA;" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_4hSaTMAnEeq6L8zfnBksuA"/>
      <link id="_4hSaS8AnEeq6L8zfnBksuA" executionCondition="${Loop/CORE_NB_EXECUTIONS}$ &lt;= ${~/P_GEN_ITERATION}$" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_4hSaVMAnEeq6L8zfnBksuA"/>
    </actionCode>
    <actionCode id="_4hSaTMAnEeq6L8zfnBksuA" isBeginAction="false" name="EndLoop" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI"/>
    <actionCode id="_4hSaTcAnEeq6L8zfnBksuA" isBeginAction="false" name="Left" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="_4hSaTsAnEeq6L8zfnBksuA" executionType="OK" generationType="OK_KO" mandatory="0" targetId="_4hSaUcAnEeq6L8zfnBksuA"/>
    </actionCode>
    <actionCode id="_4hSaT8AnEeq6L8zfnBksuA" isBeginAction="false" name="Right" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="_4hSaUMAnEeq6L8zfnBksuA" executionType="OK" generationType="OK_KO" mandatory="0" targetId="_4hSaUcAnEeq6L8zfnBksuA"/>
    </actionCode>
    <actionCode id="_4hSaUcAnEeq6L8zfnBksuA" isBeginAction="false" name="Synchro" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
      <link id="_4hSaUsAnEeq6L8zfnBksuA" executionCondition="'${~/P_GEN_CONDITIONAL_ACTION}$' == 'TRUE'" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_4hSaWcAnEeq6L8zfnBksuA"/>
      <link id="_4hSaU8AnEeq6L8zfnBksuA" executionCondition="'${~/P_GEN_CONDITIONAL_ACTION}$' != 'TRUE'" executionType="OK" generationType="OK_KO" mandatory="0" targetId="_4hSaScAnEeq6L8zfnBksuA"/>
    </actionCode>
    <actionCode id="_4hSaVMAnEeq6L8zfnBksuA" isBeginAction="false" name="Normal Sleep" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JSleepActionCodeI">
      <link id="_4hSaVcAnEeq6L8zfnBksuA" executionCondition="'${~/P_GEN_DIRECTION_DECISION}$' == 'RIGHT'" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_4hSaT8AnEeq6L8zfnBksuA"/>
      <link id="_4hSaVsAnEeq6L8zfnBksuA" executionCondition="'${~/P_GEN_DIRECTION_DECISION}$' == 'LEFT'" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_4hSaTcAnEeq6L8zfnBksuA"/>
      <link id="_4hSaV8AnEeq6L8zfnBksuA" executionCondition="'${~/P_GEN_DIRECTION_DECISION}$' != 'LEFT' &amp;&amp; '${~/P_GEN_DIRECTION_DECISION}$' != 'RIGHT'" executionType="OK" generationType="OK_KO" mandatory="0" targetId="_4hSaUcAnEeq6L8zfnBksuA"/>
      <parameter id="_4hSaWMAnEeq6L8zfnBksuA" name="SLEEP_DELAY" type="String" value="${~/P_GEN_SLEEP_PERIOD}$000"/>
    </actionCode>
    <actionCode id="_4hSaWcAnEeq6L8zfnBksuA" isBeginAction="false" name="Conditional Sleep" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JSleepActionCodeI">
      <link id="_4hSaWsAnEeq6L8zfnBksuA" executionType="OK" generationType="OK_KO" mandatory="0" targetId="_4hSaScAnEeq6L8zfnBksuA"/>
      <parameter id="_4hSaW8AnEeq6L8zfnBksuA" name="SLEEP_DELAY" type="String" value="${~/P_GEN_SLEEP_PERIOD}$000"/>
    </actionCode>
  </subProcess>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.2/notation#/?fileId=_4hSaQcAnEeq6L8zfnBksuA?">
  <notation:Diagram xmi:id="150c7127-3871-474a-87d6-d0f607d52884" type="Proc" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="b1c2d341-fb04-4292-8b8d-b08641d83349" type="2004">
      <children xmi:type="notation:Node" xmi:id="fdd1aa49-0237-4028-b74f-a3eca9235a67" type="5004"/>
      <children xmi:type="notation:Node" xmi:id="09747770-2ee6-414b-8d77-13d11dff90a5" type="7005">
        <styles xmi:type="notation:DrawerStyle" xmi:id="318e2f2a-c4f6-4a82-b137-11fb37424a9b"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="7d85c0c5-97d1-4e4d-8ada-db8f4fa074e6"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="bae01146-be4c-4684-b8c7-9e844731bba9"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="c2500229-66c8-4ff7-bf19-b5a800ab175a" type="7006">
        <styles xmi:type="notation:DrawerStyle" xmi:id="25788710-52e6-4850-8872-ff1172aad92a"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="6e451e31-0f32-4e59-81e2-9b4556d9592c"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="a10489f5-68df-4c32-b9c2-0e2475349fe6"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="23b0bb58-0071-481a-9b3a-9b1929cec3f5" fontName="Segoe UI"/>
      <styles xmi:type="notation:HintedDiagramLinkStyle" xmi:id="9a01aec1-8b2a-442e-87b5-bf52ff0107b7"/>
      <element xmi:type="proc:SubActionProcess" href="../../P1.proc#_4hSaR8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Process%20body?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="f9ec036c-6acf-4bdf-a330-49e6ffd90164" x="30" y="132"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="69da06ef-dab0-49e1-a1c4-2c625091f29a" type="2003">
      <children xmi:type="notation:Node" xmi:id="0d090a48-836f-49b5-ba28-23c78a19dc1a" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="06c238ce-dd47-45f7-a3a5-8f741ec39418" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="d7d49c81-ce8b-4da0-992a-d36c335c3038" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="258ccba4-3d37-417d-b862-cf48ed06f7cf"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="be5d8f5d-8435-48bc-887a-70179c61707a"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="6ea3b983-d98b-4e3e-aabf-731a28c4b497" type="7004">
        <children xmi:type="notation:Node" xmi:id="_y-wLgMUZEeqlFMxK4WGtuA" type="3004">
          <element xmi:type="proc:MetaDataLink" href="../../P1.proc#31c00411-9ab7-4bdf-b089-29d61904b701?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
          <layoutConstraint xmi:type="notation:Location" xmi:id="_y-wLgcUZEeqlFMxK4WGtuA"/>
        </children>
        <styles xmi:type="notation:DrawerStyle" xmi:id="726732af-b436-4122-97b9-1635cc1addaa"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="f07656c3-53b4-425f-8309-a97aac66f39a"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="b786a419-b39c-4d14-b0d3-7618b1f1c42a"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="2d1d71e1-d195-48fe-9e48-47c29e3419f6" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="../../P1.proc#_4hSaQsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=get%20Errors?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="15e0c718-143d-4784-833b-20d58802804c" x="126" y="234"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="9219786d-318b-4dca-b7a6-2d67664a4204" type="2003">
      <children xmi:type="notation:Node" xmi:id="adcfacd3-b9f2-489c-8c84-04e13e8a5347" type="5003"/>
      <children xmi:type="notation:Node" xmi:id="5e368ab1-6db6-4504-b314-edda6bcf75d2" type="7003">
        <styles xmi:type="notation:DrawerStyle" xmi:id="d7e75f36-c280-416e-835d-f27c7056da39" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="5872bdce-5637-47fe-8ae4-f3b5ee1883e3"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="85c08512-a369-4e2f-a27a-96095f6cef54"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="122919f7-3291-4e5e-9f7e-6e2d0ccde5c7" type="7004">
        <styles xmi:type="notation:DrawerStyle" xmi:id="ae139cd2-7855-4524-8a34-b8592b381474"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="74e6193a-2dfd-49f7-b591-648d9e95db1f"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="7e8acea1-fc4d-4fc0-8cc7-35deca144502"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="5bfaba10-4a56-473d-9b7c-c49b4ad08e08" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionProcessRef" href="../../P1.proc#_4hSaRMAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Init%20parameters?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="076a8d97-7fb8-4be9-b48f-3e1bb1b6a049" x="138" y="30"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="f5fac067-29c4-4584-9d94-b6e9265af1d2"/>
    <element xmi:type="proc:ActionProcess" href="../../P1.proc#_4hSaQcAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=P1?"/>
    <edges xmi:type="notation:Edge" xmi:id="05059647-5fe2-4b60-b2da-258eee14ddc7" type="4001" source="9219786d-318b-4dca-b7a6-2d67664a4204" target="b1c2d341-fb04-4292-8b8d-b08641d83349">
      <styles xmi:type="notation:RoutingStyle" xmi:id="f5afed40-5162-4b13-8489-dda38ffc8a79"/>
      <styles xmi:type="notation:FontStyle" xmi:id="3d037625-7e4b-428a-a0c4-124a3331814d" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaRcAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="4df1f000-dd1b-4a08-bd11-556efccb46d4" points="[0, 0, 76, -60]$[-76, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="e6fb505b-4808-4856-b51d-44bcb7257ceb" id="(0.2463768115942029,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="fb47eb39-ec4d-4a3c-8597-47046d29cdf4" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="f4aa7106-7336-42fc-a524-b51b95771970" type="4001" source="9219786d-318b-4dca-b7a6-2d67664a4204" target="69da06ef-dab0-49e1-a1c4-2c625091f29a">
      <styles xmi:type="notation:RoutingStyle" xmi:id="1534f09a-46b1-412d-b274-c9f4078f9b9b"/>
      <styles xmi:type="notation:FontStyle" xmi:id="aed94d56-a4ef-4412-b36f-6c00c2c66d28" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaRsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="0bef53e7-16de-4b5f-b507-e96eafcc9063" points="[0, 0, 0, -164]$[0, 164, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="34d3deb4-fe54-49d6-96a0-b47616967116" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="45b78f05-c8ca-4478-8ecb-8bdc8ef17891" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="417e006e-e9ae-4e56-a5c7-bd2a02d59ed2" type="4001" source="b1c2d341-fb04-4292-8b8d-b08641d83349" target="69da06ef-dab0-49e1-a1c4-2c625091f29a">
      <styles xmi:type="notation:RoutingStyle" xmi:id="083bf53d-c7a6-4868-9599-cc56d7f50093"/>
      <styles xmi:type="notation:FontStyle" xmi:id="675dfa56-c027-4eae-94c6-1c79c899bbc1" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaSMAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="a81147e1-44d6-4b03-a544-26d50de49933" points="[0, 0, -71, -60]$[71, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="eb20a90e-bb46-471a-a0de-b21bb567ef10" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="eca61878-2f68-4d25-a60f-f6b77d7e1bb1" id="(0.2468354430379747,0.0)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="c7d50d0c-b7ad-4455-b33a-923a4e275b99" type="Proc" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="5f69d10f-9d45-49e4-a20f-051f48e86529" type="2001">
      <children xmi:type="notation:Node" xmi:id="c08cc5e5-97aa-4e3b-bdfa-0812a4459c2c" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="eda0b0ff-05d9-4624-ad8e-4d8a04e15a08" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="2419395f-6e91-4501-ab7d-16dbdf91d20b"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="c46cc644-e179-4f41-98ed-6f4e059addf3"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="c50d6a0b-c6ef-46b7-955b-5afc5fe78e85"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="d4f6acb4-4a6a-411b-a301-eaf909f36879" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="7c190509-d9c6-4835-bb66-aa391d0e536e"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="f75d6fe2-81b3-4190-85e2-4f8756c3f6e3"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="db2ee560-6a0d-4e3d-9092-7a48d46ce8aa"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="4c5bda04-31d7-4264-a1ef-9dba7b24e0c5" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaScAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Loop?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="d3cb056d-e720-42b5-a575-efb474a1381d" x="246" y="438"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="4ac55457-bc05-43d6-9539-27edcba970aa" type="2001">
      <children xmi:type="notation:Node" xmi:id="7dbcc78a-9cc3-407b-8cda-b489f49fd9ec" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="c7f2c517-b9ca-49ee-9f9d-63086c893e34" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="d0c03b42-0b5b-4ea1-9d62-a9c72597f600"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="581b3d0c-f4bf-470d-92ba-487f5896850b"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="919f1982-235b-4a8a-a9f2-238f71789eaa"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="8b85acd1-cf1d-4a24-b217-e797f0aebeb3" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="ffa8a41f-7f1b-4dd9-b7ab-88e58979d197"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="2e671e79-c580-43d6-b991-8c0b260356ba"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="6ecdafc7-8766-46c2-aa89-11d96b929e44"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="b2375a50-1509-4334-837d-9bf199242516" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaTMAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=EndLoop?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="10ff9e3f-786b-46c9-a3ca-129c75dd866d" x="240" y="546"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="01b23a30-a78e-47ed-b1d5-bfd6101c6afb" type="2001">
      <children xmi:type="notation:Node" xmi:id="06f5a555-00a2-491f-8842-8d15111af125" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="557fc3ac-7c3a-4451-83b9-abcb63e3e9d7" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="0e49987b-8d8b-4058-8cf6-fe5355d45008"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="afd28816-7d74-4794-bea9-bfedd125f002"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="f40c6d0e-564d-4594-a79d-1686fcdbca46"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="17ea1337-8428-40e8-b1c7-8792ce09c32a" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="c97266a5-17d2-4dfd-ae6d-7bc661caf118"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="17069f1d-8452-4c9b-839a-f3e876727abf"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="18446016-64b0-41c7-abb8-94586e60b005"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="a4143b3a-fe49-49fd-bc28-74b6fed0e24b" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaTcAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Left?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="ef7e50e8-7b54-40eb-b70b-05d9e185d060" x="30" y="132"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="83fddcc9-b74b-4e3f-9cd2-1a3e9c27de26" type="2001">
      <children xmi:type="notation:Node" xmi:id="0625d5ea-43c7-4f66-bfd5-907ce46ff710" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="0c021921-3c0d-4583-b487-13a091224f30" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="ea6edb4a-fe32-4ec6-9a86-fff44cddb505"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="3095ab9f-7c93-4e36-b652-aac41eba8a74"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="20c6a665-789c-460d-868d-12efa5e9d991"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="7ff84e7a-b957-45ba-b926-83fe88c73a35" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="ff75bf28-f055-4133-b011-1af3483d578e"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="0ded47ce-34e8-4e75-addb-9aa4852fdeac"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="1c208375-053e-4462-ad57-33e002a0f142"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="15ceb7d9-bbfe-4cee-b233-0de9cb4cad5a" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaT8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Right?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="d550ec82-20a9-475d-bfe6-2ebabc6aa553" x="168" y="132"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="2900ffbe-11ab-4e4c-857e-96fe0041dd57" type="2001">
      <children xmi:type="notation:Node" xmi:id="51a382a9-4906-4ddb-9bf6-64b7e8a6f57c" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="eac923e4-fda1-4728-a91e-a9e77de48d77" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="0322de95-f9dc-4518-a436-ac7a0ac90e93"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="3ef7955f-7a32-4d88-8925-9f5fe0d8e436"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="e7e7e238-3148-4dbf-8e39-d8a04f834c84"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="5fd6dc65-29d5-4d6f-8868-c9d16a5f3486" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="e0bc9bff-d242-4827-aa18-aa71f56007f4"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="05ccb24a-6a53-4cb4-8482-f73bd175ea96"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="550e1588-b08a-4432-a127-c58cdc02aead"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="e27ee64f-4e19-4e89-bc32-7eb809f6ac5e" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaUcAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Synchro?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="80874958-06c2-46b2-8e87-a731428034b3" x="180" y="234"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="0bd65ca2-8a29-4d2a-a00e-46b76b17d6b8" type="2001">
      <children xmi:type="notation:Node" xmi:id="b4d269f5-89f1-40ce-b0ac-c6598498ff3b" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="648b8fba-37a7-4cfc-9ed9-080f900109b6" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="8be705b7-fc73-4ddc-9103-a3fa3d695dbe" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="1794a4f9-5b04-4ce1-935b-eb23d4aaa7df"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="8046b516-8d56-4d4d-8a4b-7039dc488599"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="66d93ff0-999c-4cd0-b03a-640f24760dce" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="7eedd318-cc02-4a3f-a685-538184d79ad4"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="3f41114d-f650-45f0-a368-269c270c70ef"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="7d8dd51b-4a38-47bb-83bc-7d13e6cc3b3a"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="05ab109e-2cb2-4063-a368-cd5611cb1111" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaVMAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Normal%20Sleep?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="2bd5b750-194b-412b-aae1-bf03ddab001b" x="228" y="30"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="452e508d-87a7-42ee-918e-b6abe2ef5b48" type="2001">
      <children xmi:type="notation:Node" xmi:id="17a3d66d-b897-4f52-8715-53567282a910" type="5001"/>
      <children xmi:type="notation:Node" xmi:id="37f36b0d-311a-4499-885a-b960983e2d47" type="7001">
        <styles xmi:type="notation:DrawerStyle" xmi:id="841320e6-03f6-44b9-980b-6fc72a0d9fab" collapsed="true"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="8cdb65bb-0025-4cf8-a635-a81a7317ab6c"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="56b42e81-a797-402a-98ba-d4c6c83296cd"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="9fd64749-dd2a-4f56-847a-965be3289fa4" type="7002">
        <styles xmi:type="notation:DrawerStyle" xmi:id="f535c25c-73f2-4133-9b0c-8fc4602cf850"/>
        <styles xmi:type="notation:SortingStyle" xmi:id="7a0f443b-8a6a-427e-8134-b28ade89ccd7"/>
        <styles xmi:type="notation:FilteringStyle" xmi:id="ff196f2d-bdd1-428b-82f7-35a3f4a2d4a6"/>
      </children>
      <styles xmi:type="notation:ShapeStyle" xmi:id="426f8413-ba5b-4511-83ac-012fd503ee99" fontName="Segoe UI"/>
      <element xmi:type="proc:ActionCode" href="../../P1.proc#_4hSaWcAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Conditional%20Sleep?"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="8ff35cb6-8f0e-4515-9875-aac2f758fe40" x="84" y="336"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="b329d413-37de-434a-94d5-3ab72d2e7d60"/>
    <element xmi:type="proc:SubActionProcess" href="../../P1.proc#_4hSaR8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc$name=Process%20body?"/>
    <edges xmi:type="notation:Edge" xmi:id="a3b4c948-41bf-4d9b-8f17-17bfd37d64c7" type="4001" source="5f69d10f-9d45-49e4-a20f-051f48e86529" target="4ac55457-bc05-43d6-9539-27edcba970aa">
      <styles xmi:type="notation:RoutingStyle" xmi:id="7eb82d8e-9185-44bd-9329-032e90050f39"/>
      <styles xmi:type="notation:FontStyle" xmi:id="7bf0c798-8f7a-4730-9331-de422c636556" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaSsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="e5655a49-3146-4f36-b3f8-e79cefbe065b" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="ffa1181a-d47a-48d6-a6ff-c2a99bb28847" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="549259e9-7cde-4e1b-b4c0-bf83879035ca" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="67d61aea-f958-467b-a845-c7236c15116f" type="4001" source="5f69d10f-9d45-49e4-a20f-051f48e86529" target="0bd65ca2-8a29-4d2a-a00e-46b76b17d6b8">
      <styles xmi:type="notation:RoutingStyle" xmi:id="629824ed-0c99-45ed-8ef9-19df894a73c1"/>
      <styles xmi:type="notation:FontStyle" xmi:id="7354ce1a-8f54-4aab-81ea-89921763515b" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaS8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="aff199e4-8780-4014-bc56-c88b992dde0c" points="[0, 0, 0, 369]$[0, -369, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="0f2fc47e-7fef-454e-a782-7d7926cbec5d" id="(0.8061224489795918,0.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="8721d90c-8a30-4612-88da-153958ba82e8" id="(0.7153284671532847,1.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="7d0b455b-6b86-4522-8fd6-9718a4f41b7b" type="4001" source="01b23a30-a78e-47ed-b1d5-bfd6101c6afb" target="2900ffbe-11ab-4e4c-857e-96fe0041dd57">
      <styles xmi:type="notation:RoutingStyle" xmi:id="5be1722f-554c-4ba5-a9c9-503920a91df4"/>
      <styles xmi:type="notation:FontStyle" xmi:id="f9cf1a9a-fb9d-44d3-a69e-99dbcd9264e7" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaTsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="c09e800b-4b47-458a-801f-7d022db3c007" points="[0, 0, -125, -60]$[125, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="c1503c8c-cb8a-4baf-8259-0714b1dc8a0d" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="b0e5df86-ed77-4955-b660-0d70cc27e9e9" id="(0.14,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="63da4343-5ac3-47fc-883f-a410ddb59662" type="4001" source="83fddcc9-b74b-4e3f-9cd2-1a3e9c27de26" target="2900ffbe-11ab-4e4c-857e-96fe0041dd57">
      <styles xmi:type="notation:RoutingStyle" xmi:id="0d2e54f6-b8e9-44fb-bb42-a4c9bd90e1cd"/>
      <styles xmi:type="notation:FontStyle" xmi:id="5f522b6f-a3cd-4b89-ad9a-46ed375d4d66" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaUMAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="48180a52-3528-4e8b-adbe-487ea1547a58" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="f1252553-5265-4865-9f43-366b6d690502" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="610c3b5b-67ca-4520-b420-97a3c3557d00" id="(0.29,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="ccd7aa50-e092-42c1-a4ac-ad48d8502b1f" type="4001" source="2900ffbe-11ab-4e4c-857e-96fe0041dd57" target="452e508d-87a7-42ee-918e-b6abe2ef5b48">
      <styles xmi:type="notation:RoutingStyle" xmi:id="896eecc8-6ab1-405b-aaba-762ccb2981cd"/>
      <styles xmi:type="notation:FontStyle" xmi:id="716c366f-9548-40ee-a79b-dc6ced15a149" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaUsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="8ce131b3-8f03-4f96-bddd-612246d6989a" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="11553deb-a255-41b5-8476-15145bf40b82" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="4986fe8d-34e1-4a92-8ad6-234d00d6ad52" id="(0.8869047619047619,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="a5cab0f9-7435-44ed-bc63-f6e2b8685455" type="4001" source="2900ffbe-11ab-4e4c-857e-96fe0041dd57" target="5f69d10f-9d45-49e4-a20f-051f48e86529">
      <styles xmi:type="notation:RoutingStyle" xmi:id="6a2ff105-cd1d-4b68-a4f5-302bd41078a3"/>
      <styles xmi:type="notation:FontStyle" xmi:id="0a03d853-ed4f-43ae-879d-b55603092ee7" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaU8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="5fcb8655-a4a1-46a6-92ca-6d5d51b95e0e" points="[0, 0, -38, -161]$[38, 60, 0, -101]$[38, 161, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="46e97d0d-dad1-417c-b0f2-1d504f381c33" id="(0.75,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="974e8cda-31ba-4d94-b5b6-da03b47b81cc" id="(0.4897959183673469,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="15be205c-f515-44ff-9d23-416eac353bc1" type="4001" source="0bd65ca2-8a29-4d2a-a00e-46b76b17d6b8" target="83fddcc9-b74b-4e3f-9cd2-1a3e9c27de26">
      <styles xmi:type="notation:RoutingStyle" xmi:id="0f8a9411-fc0a-4cd0-908b-dfd7034d4cb6"/>
      <styles xmi:type="notation:FontStyle" xmi:id="63bba767-965d-448c-a4d3-253243272675" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaVcAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="cbf7fb4b-a0ee-4f9d-bb2f-556f4c987e2d" points="[0, 0, 61, -60]$[-61, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="8e6dfccc-dcb6-4405-be76-d000e76de6f9" id="(0.32116788321167883,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="3c34f6a1-acfd-4a9d-8be6-f9d0a4536ea3" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="1c4eaa6b-9e84-4e00-bb60-0003a8bd2bac" type="4001" source="0bd65ca2-8a29-4d2a-a00e-46b76b17d6b8" target="01b23a30-a78e-47ed-b1d5-bfd6101c6afb">
      <styles xmi:type="notation:RoutingStyle" xmi:id="42150cb3-3488-42f6-bc78-13f98526284a"/>
      <styles xmi:type="notation:FontStyle" xmi:id="44ac7c43-7d98-465f-93a8-c02273198791" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaVsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="b847ea8b-506c-4ddb-98e3-82f20c20ebb1" points="[0, 0, 179, -60]$[-179, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="c619a448-9362-4ec4-bd94-0e3d746d6d5a" id="(0.16058394160583941,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="2435bd2f-ef86-4661-9548-710c3f7d395d" id="(0.5,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="7685549c-9429-4c67-a348-75602114210b" type="4001" source="0bd65ca2-8a29-4d2a-a00e-46b76b17d6b8" target="2900ffbe-11ab-4e4c-857e-96fe0041dd57">
      <styles xmi:type="notation:RoutingStyle" xmi:id="b2cd4d55-0aa0-4c20-bd8c-44f6f54ba756"/>
      <styles xmi:type="notation:FontStyle" xmi:id="58dce42c-bae1-47c5-94f2-6ab2812fc6f6" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaV8AnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="a2040814-b6db-451d-b421-7ca60706cd27" points="[0, 0, 49, -164]$[0, 103, 49, -61]$[-49, 164, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="04680daa-cd81-4f2d-ba33-40684edc0713" id="(0.48905109489051096,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="8a8d9284-d3be-4f8e-997c-838dbe8cd018" id="(0.64,0.0)"/>
    </edges>
    <edges xmi:type="notation:Edge" xmi:id="ae50cd20-429b-421c-b835-3fab1a898832" type="4001" source="452e508d-87a7-42ee-918e-b6abe2ef5b48" target="5f69d10f-9d45-49e4-a20f-051f48e86529">
      <styles xmi:type="notation:RoutingStyle" xmi:id="56af9576-d566-44b3-87a0-f146aab749d1"/>
      <styles xmi:type="notation:FontStyle" xmi:id="61a8bcdc-062c-4fe1-816b-d0301b64b6f6" fontName="Segoe UI"/>
      <element xmi:type="proc:Link" href="../../P1.proc#_4hSaWsAnEeq6L8zfnBksuA?fileId=_4hSaQcAnEeq6L8zfnBksuA$type=proc?"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="e9ec4d5a-b24e-455d-b2c8-4c69e91dc988" points="[0, 0, -104, -60]$[104, 60, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="4784f9bd-c85f-4d22-aea9-a757bab9c7e0" id="(0.5,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="5f381e50-f658-4612-bf2f-613da199c383" id="(0.24489795918367346,0.0)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
]]></diagram>
</proc:process>