<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="a1a9e0c9-0f45-45e2-8ff5-279da5c6e510">
  <actionCode id="4e29a66d-9dbd-4fb0-9f02-2b1a26a97443" isBeginAction="false" name="v_cus_id" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.VariableManagerActionCodeI">
    <link id="bb0a0017-3725-4fa7-94e1-0c9a5f75c244" executionType="OK" generationType="OK_KO" mandatory="1" targetId="795421bf-1a20-4cc5-9ff9-2dedf95ac82f"/>
    <metaDataLink id="00efd031-30f1-4cbc-984c-c7d69d5e8f69" name="v_cus_id" target="resource.md#_WKvnsJmkEeyjqJcu_tQBzg?fileId=_MIaAEJmkEeyjqJcu_tQBzg$type=md$name=v_cus_id?" visibility="parent"/>
    <parameter id="1ba00242-8b39-4ad1-8ae5-f884b07e1c68" name="VAR_OPERATION" type="String" value="SetValue"/>
    <parameter id="6d7e81c4-c509-4ae8-afe1-918841e92305" name="VAR_VALUE" type="String" value="50"/>
  </actionCode>
  <actionProcessRef id="795421bf-1a20-4cc5-9ff9-2dedf95ac82f" isBeginAction="false" name="Generate xml customerDetails VAR" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_pYrKXJmmEeyjqJcu_tQBzg?fileId=_pYrKXJmmEeyjqJcu_tQBzg$name=Generate%20xml%20customerDetails%20VAR$type=map?"/>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=a1a9e0c9-0f45-45e2-8ff5-279da5c6e510?" xmi:id="_v1XZgJmpEeyKWdtwmwVPOQ" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_wiC5UJmpEeyKWdtwmwVPOQ" type="2003">
    <children xmi:type="notation:Node" xmi:id="_wiF8oJmpEeyKWdtwmwVPOQ" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_wiF8oZmpEeyKWdtwmwVPOQ" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_wiF8opmpEeyKWdtwmwVPOQ" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_wiF8o5mpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_wiF8pJmpEeyKWdtwmwVPOQ"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_wiF8pZmpEeyKWdtwmwVPOQ" type="7004">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_wiF8ppmpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_wiF8p5mpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_wiF8qJmpEeyKWdtwmwVPOQ"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_wiC5UZmpEeyKWdtwmwVPOQ" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#795421bf-1a20-4cc5-9ff9-2dedf95ac82f?fileId=a1a9e0c9-0f45-45e2-8ff5-279da5c6e510$type=proc$name=Generate%20xml%20customerDetails%20VAR?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wiC5UpmpEeyKWdtwmwVPOQ" x="30" y="180"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_x47MsJmpEeyKWdtwmwVPOQ" type="2001">
    <children xmi:type="notation:Node" xmi:id="_x49o8JmpEeyKWdtwmwVPOQ" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_x49o8ZmpEeyKWdtwmwVPOQ" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_x49o8pmpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_x49o85mpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_x49o9JmpEeyKWdtwmwVPOQ"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_x49o9ZmpEeyKWdtwmwVPOQ" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_x49o9pmpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_x49o95mpEeyKWdtwmwVPOQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_x49o-JmpEeyKWdtwmwVPOQ"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_x47MsZmpEeyKWdtwmwVPOQ" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#4e29a66d-9dbd-4fb0-9f02-2b1a26a97443?fileId=a1a9e0c9-0f45-45e2-8ff5-279da5c6e510$type=proc$name=v_cus_id?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x47MspmpEeyKWdtwmwVPOQ" x="55" y="30"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_v1XZgZmpEeyKWdtwmwVPOQ"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#a1a9e0c9-0f45-45e2-8ff5-279da5c6e510?fileId=a1a9e0c9-0f45-45e2-8ff5-279da5c6e510$type=proc$name=Update%20variable%20and%20execute%20mapping?"/>
  <edges xmi:type="notation:Edge" xmi:id="_y0NwQJmpEeyKWdtwmwVPOQ" type="4001" source="_x47MsJmpEeyKWdtwmwVPOQ" target="_wiC5UJmpEeyKWdtwmwVPOQ">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_y0NwQZmpEeyKWdtwmwVPOQ"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_y0NwQpmpEeyKWdtwmwVPOQ" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#bb0a0017-3725-4fa7-94e1-0c9a5f75c244?fileId=a1a9e0c9-0f45-45e2-8ff5-279da5c6e510$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y0NwQ5mpEeyKWdtwmwVPOQ" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y0O-YJmpEeyKWdtwmwVPOQ" id="(0.5,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1oenoJmpEeyKWdtwmwVPOQ" id="(0.4978902953586498,0.0)"/>
  </edges>
</notation:Diagram>
]]></diagram>
</proc:process>