<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="eb1623bb-1305-465a-9a71-1be96d513b13">
  <actionProcessRef id="f473fa4e-e5f4-4465-97b7-ad82e8747d30" isBeginAction="false" name="TOOL_DBSchemaReport" nbCycles="-1" toleratedError="false" targetName="resource.proc#b44673c0-1536-4204-9ba5-be2d1b097b9e?fileId=b44673c0-1536-4204-9ba5-be2d1b097b9e$type=proc$name=TOOL_DBSchemaReport?">
    <metaDataLink id="22cc6ffb-ec40-42fe-82f9-81cced6a6c54" name="TARGET_FOLDER" target="resource.md#_lTNZAYifEeuWgJC3_Kx5pQ?fileId=_lTNZAIifEeuWgJC3_Kx5pQ$type=md$name=Report_Folder?"/>
    <metaDataLink id="9ac64366-53c0-47b2-b6a1-759fda593115" name="TARGET_SCHEMA" target="resource.md#_RwuYcJb8EeytipfABCJWjQ?fileId=_50xksJMhEeymq6fNOAxqGA$type=md$name=datamart.hotel_datamart?"/>
  </actionProcessRef>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=eb1623bb-1305-465a-9a71-1be96d513b13?" xmi:id="_DpBMwIiTEeuWgJC3_Kx5pQ" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_HfiLUIiTEeuWgJC3_Kx5pQ" type="2003">
    <children xmi:type="notation:Node" xmi:id="_HfquMIiTEeuWgJC3_Kx5pQ" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_Hfr8UIiTEeuWgJC3_Kx5pQ" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Hfr8UYiTEeuWgJC3_Kx5pQ" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Hfr8UoiTEeuWgJC3_Kx5pQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Hfr8U4iTEeuWgJC3_Kx5pQ"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_HftxgIiTEeuWgJC3_Kx5pQ" type="7004">
      <children xmi:type="notation:Node" xmi:id="_YcLtEJC_EeuL3MkGbndtFw" type="3004">
        <element xmi:type="proc:MetaDataLink" href="resource.proc#22cc6ffb-ec40-42fe-82f9-81cced6a6c54?fileId=eb1623bb-1305-465a-9a71-1be96d513b13$type=proc?"/>
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YcLtEZC_EeuL3MkGbndtFw"/>
      </children>
      <children xmi:type="notation:Node" xmi:id="_si5KEKEmEey6HJjlkOrxiQ" type="3004">
        <element xmi:type="proc:MetaDataLink" href="resource.proc#9ac64366-53c0-47b2-b6a1-759fda593115?fileId=eb1623bb-1305-465a-9a71-1be96d513b13$type=proc?"/>
        <layoutConstraint xmi:type="notation:Location" xmi:id="_si5KEaEmEey6HJjlkOrxiQ"/>
      </children>
      <styles xmi:type="notation:DrawerStyle" xmi:id="_HftxgYiTEeuWgJC3_Kx5pQ"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_HftxgoiTEeuWgJC3_Kx5pQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Hftxg4iTEeuWgJC3_Kx5pQ"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_HfiLUYiTEeuWgJC3_Kx5pQ" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#f473fa4e-e5f4-4465-97b7-ad82e8747d30?fileId=eb1623bb-1305-465a-9a71-1be96d513b13$type=proc$name=TOOL_DBSchemaReport?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HfiLUoiTEeuWgJC3_Kx5pQ" x="153" y="119"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_DpBMwYiTEeuWgJC3_Kx5pQ"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#eb1623bb-1305-465a-9a71-1be96d513b13?fileId=eb1623bb-1305-465a-9a71-1be96d513b13$type=proc$name=Gen_MX_DBSchemaReport?"/>
</notation:Diagram>
]]></diagram>
</proc:process>