<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="29179175-7384-4f3b-8cd1-2f4b207f6b8a">
  <actionCode id="d9d5c599-889a-4257-aa87-cf449806c7fb" isBeginAction="false" name="SqlOperation" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JdbcActionCodeI">
    <bindLink id="be10b815-00ef-43a5-92c4-ff87b45c4c5b" bindType="DirectBind" targetId="6a9b825b-4384-4907-8808-6ce8d0ddb7e8"/>
    <metaDataLink id="d9a10b86-8045-412d-aec4-77b8f2bc1a02" name="t_customer" target="resource.md#_NwwbkZb_EeytipfABCJWjQ?fileId=_DS58oJb_EeytipfABCJWjQ$type=md$name=t_customer?"/>
    <parameter id="aafb4a7e-aa0a-4bf8-9ca4-fd055846e601" name="SQL_CONNECTION" type="String"/>
    <parameter id="5b2b92d8-99eb-41b4-90d0-e1049f079180" name="SQL_ACTION_TYPE" type="String" value="SELECT"/>
    <code>WITH   lst1(id1,terme1) AS (&#xD;
SELECT 1,'Avec' FROM (VALUES(0)) UNION ALL SELECT 2,'Considérant' FROM (VALUES(0)) UNION ALL SELECT 3,'Où que nous même' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 4,'Eu égard à' FROM (VALUES(0)) UNION ALL SELECT 5,'Vu' FROM (VALUES(0)) UNION ALL SELECT 6,'En ce qui concerne' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 7,'Dans le cas particulier de' FROM (VALUES(0)) UNION ALL SELECT 8,'Quelle que soit' FROM (VALUES(0)) UNION ALL SELECT 9,'Du fait de' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 10,'Tant que durera' FROM (VALUES(0)) UNION ALL SELECT 11,'Quoi qu''on dise concernant' FROM (VALUES(0)) UNION ALL SELECT 12,'Nonobstant' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 13,'Malgré' FROM (VALUES(0)) UNION ALL SELECT 14,'Pour réagir face à' FROM (VALUES(0)) UNION ALL SELECT 15,'Afin de circonvenir à' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 16,'Dans le but de pallier à' FROM (VALUES(0)) UNION ALL SELECT 17,'Si vous voulez mon avis concernant' FROM (VALUES(0))),&#xD;
       lst2(id2,terme2) AS (&#xD;
SELECT 1,'la restriction' FROM (VALUES(0)) UNION ALL SELECT 2,'l''orientation' FROM (VALUES(0)) UNION ALL SELECT 3,'la crise' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 4,'l''inertie' FROM (VALUES(0)) UNION ALL SELECT 5,'la difficulté' FROM (VALUES(0)) UNION ALL SELECT 6,'l''austérité' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 7,'la dégradation' FROM (VALUES(0)) UNION ALL SELECT 8,'cette rigueur' FROM (VALUES(0)) UNION ALL SELECT 9,'la dualité de la situation' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 10,'la baisse de confiance' FROM (VALUES(0)) UNION ALL SELECT 11,'la morosité' FROM (VALUES(0)) UNION ALL SELECT 12,'la situation' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 13,'l''ambiance' FROM (VALUES(0)) UNION ALL SELECT 14,'la politique' FROM (VALUES(0)) UNION ALL SELECT 15,'la fragilité' FROM (VALUES(0)) UNION ALL&#xD;
SELECT 16,'la complexité' FROM (VALUES(0)) UNION ALL SELECT 17,'l''inconstance' FROM (VALUES(0)) UNION ALL SELECT 18,'cette inflexion' FROM (VALUES(0))),&#xD;
       lst3(id3,terme3) AS (&#xD;
SELECT 1,'présente' FROM (VALUES(0)) UNION ALL SELECT 2,'actuelle' FROM (VALUES(0)) UNION ALL SELECT 3,'générale' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'induite' FROM (VALUES(0)) UNION ALL SELECT 5,'conjoncturelle' FROM (VALUES(0)) UNION ALL SELECT 6,'observée' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'contextuelle' FROM (VALUES(0)) UNION ALL SELECT 8,'de ces derniers temps' FROM (VALUES(0)) UNION ALL SELECT 9,'de l''époque actuelle' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'intrinsèque' FROM (VALUES(0)) UNION ALL SELECT 11,'que nous constatons' FROM (VALUES(0))),&#xD;
       lst4(id4,terme4) AS (&#xD;
SELECT 1,'il convient d#' FROM (VALUES(0)) UNION ALL SELECT 2,'il faut' FROM (VALUES(0)) UNION ALL SELECT 3,'on se doit d#' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'il est préférable d#' FROM (VALUES(0)) UNION ALL SELECT 5,'il serait intéressant d#' FROM (VALUES(0)) UNION ALL SELECT 6,'il ne faut pas négliger d#' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'on ne peut se passer d#' FROM (VALUES(0)) UNION ALL SELECT 8,'il est nécessaire d#' FROM (VALUES(0)) UNION ALL SELECT 9,'il serait bon d#' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'il faut de toute urgence' FROM (VALUES(0)) UNION ALL SELECT 11,'je recommande d#' FROM (VALUES(0)) UNION ALL SELECT 12,'je préconise un audit afin d#' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 13,'il est très important d#' FROM (VALUES(0)) UNION ALL SELECT 14,'il ne faut pas s''interdire d#' FROM (VALUES(0))), &#xD;
       lst5(id5,terme5) AS (&#xD;
SELECT 1,'étudier' FROM (VALUES(0)) UNION ALL SELECT 2,'examiner' FROM (VALUES(0)) UNION ALL SELECT 3,'favoriser' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'prendre en considération' FROM (VALUES(0)) UNION ALL SELECT 5,'anticiper' FROM (VALUES(0)) UNION ALL SELECT 6,'imaginer' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'uniformiser' FROM (VALUES(0)) UNION ALL SELECT 8,'remodeler' FROM (VALUES(0)) UNION ALL SELECT 9,'avoir à l''esprit' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'se remémorer' FROM (VALUES(0)) UNION ALL SELECT 11,'gérer' FROM (VALUES(0)) UNION ALL SELECT 12,'fédérer' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 13,'comprendre' FROM (VALUES(0)) UNION ALL SELECT 14,'analyser' FROM (VALUES(0)) UNION ALL SELECT 15,'appréhender' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 16,'expérimenter' FROM (VALUES(0)) UNION ALL SELECT 17,'essayer' FROM (VALUES(0)) UNION ALL SELECT 18,'caractériser' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 19,'façonner' FROM (VALUES(0)) UNION ALL SELECT 20,'revoir' FROM (VALUES(0)) UNION ALL SELECT 21,'prendre en compte' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 22,'arrêter de stigmatiser' FROM (VALUES(0)) UNION ALL SELECT 23,'considérer' FROM (VALUES(0)) UNION ALL SELECT 24,'réorganiser' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 25,'inventorier' FROM (VALUES(0))),&#xD;
       lst6(id6,terme6) AS (&#xD;
SELECT 1,'toutes les' FROM (VALUES(0)) UNION ALL SELECT 2,'chacune des' FROM (VALUES(0)) UNION ALL SELECT 3,'la majorité des' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'la simultanéité des' FROM (VALUES(0)) UNION ALL SELECT 5,'l''ensemble des' FROM (VALUES(0)) UNION ALL SELECT 6,'la somme des' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'la totalité des' FROM (VALUES(0)) UNION ALL SELECT 8,'la globalité des' FROM (VALUES(0)) UNION ALL SELECT 9,'les relations des' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'certaines' FROM (VALUES(0)) UNION ALL SELECT 11,'la plus grande partie des' FROM (VALUES(0)) UNION ALL SELECT 12,'les principales' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 13,'systématiquement les' FROM (VALUES(0)) UNION ALL SELECT 14,'précisément les' FROM (VALUES(0)) ), &#xD;
       lst7(id7,terme7) AS (&#xD;
SELECT 1,'solutions' FROM (VALUES(0)) UNION ALL SELECT 2,'issues' FROM (VALUES(0)) UNION ALL SELECT 3,'problématiques' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'voies' FROM (VALUES(0)) UNION ALL SELECT 5,'alternatives' FROM (VALUES(0)) UNION ALL SELECT 6,'organisations matricielles' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'améliorations' FROM (VALUES(0)) UNION ALL SELECT 8,'ouvertures' FROM (VALUES(0)) UNION ALL SELECT 9,'synergies' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'actions' FROM (VALUES(0)) UNION ALL SELECT 11,'options' FROM (VALUES(0)) UNION ALL SELECT 12,'décisions' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 13,'modalités' FROM (VALUES(0)) UNION ALL SELECT 14,'hypothèses' FROM (VALUES(0)) UNION ALL SELECT 15,'stratégies' FROM (VALUES(0)) ),&#xD;
       lst8(id8,terme8) AS (&#xD;
SELECT 1,'imaginables' FROM (VALUES(0)) UNION ALL SELECT 2,'possibles' FROM (VALUES(0)) UNION ALL SELECT 3,'s''offrant à nous' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'de bon sens' FROM (VALUES(0)) UNION ALL SELECT 5,'envisageables' FROM (VALUES(0)) UNION ALL SELECT 6,'éventuelles' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'éventuelles' FROM (VALUES(0)) UNION ALL SELECT 8,'réalisables' FROM (VALUES(0)) UNION ALL SELECT 9,'déclinables' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'pertinentes' FROM (VALUES(0)) UNION ALL SELECT 11,'que nous connaissons' FROM (VALUES(0)) UNION ALL SELECT 12,'évidentes' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 13,'optimales' FROM (VALUES(0)) UNION ALL SELECT 14,'opportunes' FROM (VALUES(0)) UNION ALL SELECT 15,'emblématiques' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 16,'draconiennnes' FROM (VALUES(0))), &#xD;
       lst9(id9,terme9) AS (&#xD;
SELECT 1,'à l''avenir' FROM (VALUES(0)) UNION ALL SELECT 2,'pour le futur' FROM (VALUES(0)) UNION ALL SELECT 3,'depuis longtemps' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 4,'à court terme' FROM (VALUES(0)) UNION ALL SELECT 5,'rapidement' FROM (VALUES(0)) UNION ALL SELECT 6,'dans une perspective correcte' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 7,'avec toute la prudence requise' FROM (VALUES(0)) UNION ALL SELECT 8,'de toute urgence' FROM (VALUES(0)) UNION ALL SELECT 9,'même si ce n''est pas facile' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 10,'même si nous devons en tirer des conséquences' FROM (VALUES(0)) UNION ALL SELECT 11,'très attentivement' FROM (VALUES(0)) UNION ALL SELECT 12,'avec beaucoup de recul' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 13,'parce que la nature a horreur du vide' FROM (VALUES(0)) UNION ALL SELECT 14,'parce que nous ne faisons plus le même métier' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 15,'toutes choses étant égales par ailleurs' FROM (VALUES(0)) UNION ALL SELECT 16,'et déjà en notre possession' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 17,'en prenant toutes les précautions qui s''imposent' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 18,'si l''on veut s''en sortir' FROM (VALUES(0)) UNION ALL SELECT 19,'parce qu''il est temps d''agir' FROM (VALUES(0)) UNION ALL SELECT 20,'parce qu''il s''agit de notre dernière chance' FROM (VALUES(0)) UNION ALL &#xD;
SELECT 21,'parce que les mêmes causes produisent les mêmes effets' FROM (VALUES(0)) UNION ALL SELECT 22,'parce que nous le valons bien' FROM (VALUES(0)) ), &#xD;
       alea (id,alea_value1,alea_value2,alea_value3,alea_value4,alea_value5,alea_value6,alea_value7,alea_value8,alea_value9) AS (&#xD;
SELECT id,CAST(rand()*17+1 AS INTEGER),CAST(rand()*18+1 AS INTEGER),CAST(rand()*11+1 AS INTEGER),&#xD;
       CAST(rand()*14+1 AS INTEGER),CAST(rand()*29+1 AS INTEGER),CAST(rand()*14+1 AS INTEGER),&#xD;
       CAST(rand()*15+1 AS INTEGER),CAST(rand()*16+1 AS INTEGER),CAST(rand()*22+1 AS INTEGER)   &#xD;
FROM   UNNEST(SEQUENCE_ARRAY(1, 50, 1)) AS generate_series(id))&#xD;
SELECT CUS_ID,&#xD;
	   CUS_LAST_NAME,&#xD;
	   CUS_FIRST_NAME,&#xD;
	   CUS_ID+' '+CUS_FIRST_NAME+' '+CUS_LAST_NAME AS CUS_NAME,&#xD;
	   trim(terme1)+' '+trim(terme2)+' '+trim(terme3)+', '+&#xD;
       CASE WHEN SUBSTR(trim(terme4),LENGTH(trim(terme4)),1)='#' &#xD;
                 AND SUBSTR(trim(terme5),1,1) IN ('a','e','i','o','u','é') &#xD;
            THEN SUBSTR(trim(terme4),1,LENGTH(trim(terme4))-1)+'''' &#xD;
            ELSE SUBSTR(trim(terme4),1,LENGTH(trim(terme4))-1)+'e ' END+&#xD;
       trim(terme5)+' '+trim(terme6)+' '+trim(terme7)+' '+trim(terme8)+' '+trim(terme9) AS generated_text&#xD;
FROM   alea JOIN lst1 ON id1 = alea_value1 &#xD;
            JOIN lst2 ON id2 = alea_value2&#xD;
            JOIN lst3 ON id3 = alea_value3&#xD;
            JOIN lst4 ON id4 = alea_value4&#xD;
            JOIN lst5 ON id5 = alea_value5&#xD;
            JOIN lst6 ON id6 = alea_value6&#xD;
            JOIN lst7 ON id7 = alea_value7&#xD;
            JOIN lst8 ON id8 = alea_value8&#xD;
            JOIN lst9 ON id9 = alea_value9&#xD;
            JOIN HOTEL_MANAGEMENT.T_CUSTOMER ON CUS_ID=id&#xD;
WHERE   CUS_COMPANY='' AND TIT_CODE='Mrs' AND CUS_ID&lt;=50</code>
  </actionCode>
  <actionCode id="6a9b825b-4384-4907-8808-6ce8d0ddb7e8" isBeginAction="false" name="WriteTxtFile" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.WriteTxtFileActionCodeI">
    <metaDataLink id="0faaa5bb-d179-4fc5-9dad-2841316b38ed" name="Bind_Folder" target="resource.md#_Fc8EwLeKEeqWR_NnJH5nlg?fileId=_Fc7ds7eKEeqWR_NnJH5nlg$type=md$name=Bind_Folder?"/>
    <parameter id="a3ad0c8b-928a-47fa-9241-0dbee9ec7151" name="TXT_WRITE_FILENAME" type="String" value="%x{$Bind_Folder/tech:path()}x%/:{CUS_NAME}:.txt"/>
    <code>Dear Mrs :{CUS_LAST_NAME}: :{CUS_FIRST_NAME}:, your customer number is :{CUS_ID}: and we propose you consider reading and reflecting on the following french thought of the day  : &quot;:{generated_text}:&quot;</code>
  </actionCode>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a?" xmi:id="_34ApoDpwEe2Sj_XX78F5Wg" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_amTiwDpzEe2Sj_XX78F5Wg" type="2001">
    <children xmi:type="notation:Node" xmi:id="_amV_ADpzEe2Sj_XX78F5Wg" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_amWmEDpzEe2Sj_XX78F5Wg" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_amWmETpzEe2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_amWmEjpzEe2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_amWmEzpzEe2Sj_XX78F5Wg"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_amWmFDpzEe2Sj_XX78F5Wg" type="7002">
      <children xmi:type="notation:Node" xmi:id="_vwaJADpzEe2Sj_XX78F5Wg" type="3002">
        <element xmi:type="proc:MetaDataLink" href="resource.proc#d9a10b86-8045-412d-aec4-77b8f2bc1a02?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a$type=proc?"/>
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vwaJATpzEe2Sj_XX78F5Wg"/>
      </children>
      <styles xmi:type="notation:DrawerStyle" xmi:id="_amWmFTpzEe2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_amWmFjpzEe2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_amWmFzpzEe2Sj_XX78F5Wg"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_amTiwTpzEe2Sj_XX78F5Wg" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#d9d5c599-889a-4257-aa87-cf449806c7fb?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a$type=proc$name=SqlOperation?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_amTiwjpzEe2Sj_XX78F5Wg" x="147" y="28"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_D-E8MDp0Ee2Sj_XX78F5Wg" type="2001">
    <children xmi:type="notation:Node" xmi:id="_D-GxYDp0Ee2Sj_XX78F5Wg" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_D-GxYTp0Ee2Sj_XX78F5Wg" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_D-GxYjp0Ee2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_D-GxYzp0Ee2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_D-GxZDp0Ee2Sj_XX78F5Wg"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_D-HYcDp0Ee2Sj_XX78F5Wg" type="7002">
      <children xmi:type="notation:Node" xmi:id="_Q4T-ADp0Ee2Sj_XX78F5Wg" type="3002">
        <element xmi:type="proc:MetaDataLink" href="resource.proc#0faaa5bb-d179-4fc5-9dad-2841316b38ed?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a$type=proc?"/>
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Q4T-ATp0Ee2Sj_XX78F5Wg"/>
      </children>
      <styles xmi:type="notation:DrawerStyle" xmi:id="_D-HYcTp0Ee2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_D-HYcjp0Ee2Sj_XX78F5Wg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_D-HYczp0Ee2Sj_XX78F5Wg"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_D-E8MTp0Ee2Sj_XX78F5Wg" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#6a9b825b-4384-4907-8808-6ce8d0ddb7e8?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a$type=proc$name=WriteTxtFile?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D-E8Mjp0Ee2Sj_XX78F5Wg" x="35" y="189"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_34ApoTpwEe2Sj_XX78F5Wg"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#29179175-7384-4f3b-8cd1-2f4b207f6b8a?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a$type=proc$name=BIND_LINK?"/>
  <edges xmi:type="notation:Edge" xmi:id="_Mi1ykDp0Ee2Sj_XX78F5Wg" type="4002" source="_amTiwDpzEe2Sj_XX78F5Wg" target="_D-E8MDp0Ee2Sj_XX78F5Wg">
    <styles xmi:type="notation:ConnectorStyle" xmi:id="_Mi1ykTp0Ee2Sj_XX78F5Wg"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_Mi1ykjp0Ee2Sj_XX78F5Wg" fontName="Segoe UI"/>
    <element xmi:type="proc:BindLink" href="resource.proc#be10b815-00ef-43a5-92c4-ff87b45c4c5b?fileId=29179175-7384-4f3b-8cd1-2f4b207f6b8a$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Mi1ykzp0Ee2Sj_XX78F5Wg" points="[0, 0, 0, -60]$[0, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mi3AsDp0Ee2Sj_XX78F5Wg" id="(0.49838187702265374,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OK-OADp0Ee2Sj_XX78F5Wg" id="(0.4990859232175503,0.0)"/>
  </edges>
</notation:Diagram>
]]></diagram>
</proc:process>