DROP SCHEMA glyon CASCADE;
CREATE SCHEMA glyon;
CREATE TABLE glyon.demande
(
id_demande INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
date_demande TIMESTAMP NOT NULL,
nom_demandeur VARCHAR(100) NOT NULL,
prenom_demandeur VARCHAR(100) NOT NULL,
prenom_enfant VARCHAR(100) NOT NULL,
date_naissance_enfant DATE NOT NULL,
priorite1_demande VARCHAR(100),
priorite2_demande VARCHAR(100),
email_demandeur VARCHAR(100),
date_confirmation_inscription_glyon TIMESTAMP,
date_confirmation_inscription_demandeur TIMESTAMP,
confirmation_inscription BOOLEAN,
ville_confirmation VARCHAR(100),
niveau_confirmation INTEGER,
id_inscription_creche INTEGER,
suppression_inscription BOOLEAN);
DROP SCHEMA villeurbanne CASCADE;
DROP SCHEMA tassin CASCADE;
CREATE SCHEMA villeurbanne;
CREATE SCHEMA tassin;
CREATE TABLE villeurbanne.creche 
(
ville VARCHAR(100) NOT NULL,
niveau INTEGER,
mois_debut_niveau INTEGER,
mois_fin_niveau INTEGER,
intitule_niveau VARCHAR(100),
nb_places_niveau INTEGER);
INSERT INTO villeurbanne.creche (
SELECT 'villeurbanne',1,6,15,'Niveau 1 de 6 à 15 mois',5 FROM (VALUES(0)) UNION ALL
SELECT 'villeurbanne',2,11,26,'Niveau 2 de 11 à 26 mois',10 FROM (VALUES(0)) UNION ALL
SELECT 'villeurbanne',3,23,38,'Niveau 2 de 23 à 38 mois',15 FROM (VALUES(0)));
CREATE TABLE tassin.creche 
(
ville VARCHAR(100) NOT NULL,
niveau INTEGER,
mois_debut_niveau INTEGER,
mois_fin_niveau INTEGER,
intitule_niveau VARCHAR(100),
nb_places_niveau INTEGER);
INSERT INTO tassin.creche (
SELECT 'tassin',1,6,15,'Niveau 1 de 6 à 15 mois',3 FROM (VALUES(0)) UNION ALL
SELECT 'tassin',2,11,26,'Niveau 2 de 11 à 26 mois',5 FROM (VALUES(0)) UNION ALL
SELECT 'tassin',3,23,38,'Niveau 2 de 23 à 38 mois',8 FROM (VALUES(0)));
CREATE TABLE villeurbanne.inscription
(
id_inscription INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
id_demande INTEGER,
date_demande TIMESTAMP NOT NULL,
nom_demandeur VARCHAR(100) NOT NULL,
prenom_demandeur VARCHAR(100) NOT NULL,
prenom_enfant VARCHAR(100) NOT NULL,
date_naissance_enfant DATE NOT NULL,
date_confirmation_inscription TIMESTAMP,
niveau_confirmation INTEGER);
CREATE TABLE tassin.inscription
(
id_inscription INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
id_demande INTEGER,
date_demande TIMESTAMP NOT NULL,
nom_demandeur VARCHAR(100) NOT NULL,
prenom_demandeur VARCHAR(100) NOT NULL,
prenom_enfant VARCHAR(100) NOT NULL,
date_naissance_enfant DATE NOT NULL,
date_confirmation_inscription TIMESTAMP,
niveau_confirmation INTEGER);
DROP TABLE glyon.requete_etat_demande;
CREATE TABLE glyon.requete_etat_demande
(
id_requete_etat_demande INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
date_requete_etat_demande TIMESTAMP,
id_demande INTEGER,
date_confirmation_inscription_glyon TIMESTAMP,
date_confirmation_inscription_demandeur TIMESTAMP,
ville_confirmation VARCHAR(100),
niveau_confirmation INTEGER,
id_inscription_creche INTEGER,
intitule_reponse VARCHAR(200));