DROP SCHEMA COMPANY_ACTIVITY IF EXISTS CASCADE;
CREATE SCHEMA COMPANY_ACTIVITY;

CREATE TABLE  COMPANY_ACTIVITY.DLVRY_EXEC_LOG (EXECT_PRCS VARCHAR(100),EXECT_SEID VARCHAR(50),DLVRY_NAME VARCHAR(100),LOAD_STATUS VARCHAR(20),EXECT_START TIMESTAMP,EXECT_END TIMESTAMP)
CREATE TABLE  COMPANY_ACTIVITY.DLVRY_LINK (EXECT_PRCS VARCHAR(100),DLVRY_NAME VARCHAR(100),DLVRY_PRNT VARCHAR(100))

INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Init LOAD_ALL_DATAMART',NULL)
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load DIM_DISCOUNT','Init LOAD_ALL_DATAMART')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load DIM_PAYMENT_TYPE','Init LOAD_ALL_DATAMART')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load DIM_BEDROOM','Init LOAD_ALL_DATAMART')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load DIM_GEOGRAPHY','Init LOAD_ALL_DATAMART')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load DIM_TIME','Init LOAD_ALL_DATAMART')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load DIM_CUSTOMER','Load DIM_GEOGRAPHY')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BILLING','Load DIM_CUSTOMER')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BILLING','Load DIM_DISCOUNT')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BILLING','Load DIM_TIME')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BILLING','Load DIM_PAYMENT_TYPE')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BOOKING','Load DIM_BEDROOM')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BOOKING','Load DIM_CUSTOMER')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Load FACT_BOOKING','Load DIM_TIME')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Terminate LOAD_ALL_DATAMART','Load FACT_BOOKING')
INSERT INTO COMPANY_ACTIVITY.DLVRY_LINK VALUES ('Load ALL Datamart','Terminate LOAD_ALL_DATAMART','Load FACT_BILLING')
