DROP SCHEMA SCD IF EXISTS CASCADE;
CREATE SCHEMA SCD;
CREATE TABLE  SCD.SRC_CUSTOMER (
CUS_ID INTEGER NOT NULL,
CUS_NAME VARCHAR(100),
CUS_ADDRESS VARCHAR(100),
CUS_COMMENT VARCHAR(1000),
CONSTRAINT  PK_SRC_CUSTOMER PRIMARY KEY (CUS_ID));
INSERT INTO SCD.SRC_CUSTOMER (CUS_ID,CUS_NAME,CUS_ADDRESS,CUS_COMMENT) VALUES (1,'Maas','Germany',NULL);
INSERT INTO SCD.SRC_CUSTOMER (CUS_ID,CUS_NAME,CUS_ADDRESS,CUS_COMMENT) VALUES (2,'Souchard','France',NULL);
INSERT INTO SCD.SRC_CUSTOMER (CUS_ID,CUS_NAME,CUS_ADDRESS,CUS_COMMENT) VALUES (3,'Trump','USA',NULL);
CREATE TABLE SCD.HST_CUSTOMER (
CUS_ID INTEGER NOT NULL,
CUS_NAME VARCHAR(100),
CUS_ADDRESS VARCHAR(100),
CUS_COMMENT VARCHAR(1000),
VALID_FROM  TIMESTAMP,
VALID_TO    TIMESTAMP,
IS_VALID_VERSION INTEGER);