<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="8ed1d45e-08f0-4a74-acb9-10dac8f01554">
  <metaDataLink id="8ddee542-20ca-4f55-88f5-af4e50e73d2c" output="true" name="CustomerDetails" target="resource.md#_EjJiBzT_Ee2b_KGwvQpohQ?fileId=_EjJiBjT_Ee2b_KGwvQpohQ$type=md$name=CustomerDetails?"/>
  <parameter id="7dd017b4-7503-4fa0-abbc-0095ee822569" input="true" name="cus_id" type="Integer" value="10"/>
  <actionProcessRef id="1b1ea0b5-8527-4a09-bfb4-4a2a671dc7d2" isBeginAction="false" name="GenerateJsonCustomerDetails_WS" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_G_0_wDT_Ee2b_KGwvQpohQ?fileId=_G_0_wDT_Ee2b_KGwvQpohQ$name=GenerateJsonCustomerDetails_WS$type=map?"/>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=8ed1d45e-08f0-4a74-acb9-10dac8f01554?" xmi:id="_lUJS0DT_Ee2b_KGwvQpohQ" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_mFkvwDT_Ee2b_KGwvQpohQ" type="2005">
    <children xmi:type="notation:Node" xmi:id="_mFtSoDT_Ee2b_KGwvQpohQ" type="5005"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_mFkvwTT_Ee2b_KGwvQpohQ" fontName="Segoe UI"/>
    <element xmi:type="proc:Parameter" href="resource.proc#7dd017b4-7503-4fa0-abbc-0095ee822569?fileId=8ed1d45e-08f0-4a74-acb9-10dac8f01554$type=proc$name=cus_id?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mFkvwjT_Ee2b_KGwvQpohQ" x="771" y="105"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_skO1QDT_Ee2b_KGwvQpohQ" type="2006">
    <children xmi:type="notation:Node" xmi:id="_skR4kDT_Ee2b_KGwvQpohQ" type="5006"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_skO1QTT_Ee2b_KGwvQpohQ" fontName="Segoe UI"/>
    <element xmi:type="proc:MetaDataLink" href="resource.proc#8ddee542-20ca-4f55-88f5-af4e50e73d2c?fileId=8ed1d45e-08f0-4a74-acb9-10dac8f01554$type=proc?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_skO1QjT_Ee2b_KGwvQpohQ" x="785" y="161"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_vTXVADT_Ee2b_KGwvQpohQ" type="2003">
    <children xmi:type="notation:Node" xmi:id="_vTaYUDT_Ee2b_KGwvQpohQ" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_vTa_YDT_Ee2b_KGwvQpohQ" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_vTa_YTT_Ee2b_KGwvQpohQ" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_vTa_YjT_Ee2b_KGwvQpohQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_vTa_YzT_Ee2b_KGwvQpohQ"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_vTa_ZDT_Ee2b_KGwvQpohQ" type="7004">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_vTa_ZTT_Ee2b_KGwvQpohQ"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_vTa_ZjT_Ee2b_KGwvQpohQ"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_vTa_ZzT_Ee2b_KGwvQpohQ"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_vTXVATT_Ee2b_KGwvQpohQ" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#1b1ea0b5-8527-4a09-bfb4-4a2a671dc7d2?fileId=8ed1d45e-08f0-4a74-acb9-10dac8f01554$type=proc$name=GenerateJsonCustomerDetails_WS?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vTXVAjT_Ee2b_KGwvQpohQ" x="837" y="257"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_lUJS0TT_Ee2b_KGwvQpohQ"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#8ed1d45e-08f0-4a74-acb9-10dac8f01554?fileId=8ed1d45e-08f0-4a74-acb9-10dac8f01554$type=proc$name=getJsonCustomerDetails?"/>
</notation:Diagram>
]]></diagram>
</proc:process>