<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_ytsfwME_Eeq6L8zfnBksuA">
  <actionProcessRef id="_ytsf18E_Eeq6L8zfnBksuA" isBeginAction="false" name="get Errors" nbCycles="-1" toleratedError="false" targetName="../../../../Components/Control%20Management/TOOL_getError.proc#_mowwwYF-Eean7JATlUQCiw?fileId=_mowwwYF-Eean7JATlUQCiw$type=proc$name=TOOL_getError?">
    <metaDataLink id="c3feb8dd-3403-47a9-8099-6d8dd986f937" name="TARGET_SCHEMA" target="../20-Metadata/HSQL_Datamart.md#_yskeZsE_Eeq6L8zfnBksuA?fileId=_yskeYME_Eeq6L8zfnBksuA$type=md$name=DYNAMIC_LOAD?"/>
  </actionProcessRef>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.2/notation#/?fileId=_ytsfwME_Eeq6L8zfnBksuA?" xmi:id="13aca311-1871-410a-9a20-8a54b82cb5a6" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="b2af8332-e821-4cc1-a55f-b177666b8eaa" type="2003">
    <children xmi:type="notation:Node" xmi:id="adf7a947-0fda-4cfa-9a91-7721ead91d7c" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="03b2b51c-c282-47f1-b243-6b7a58776617" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="b69abdfe-b3b9-4a4b-afa8-061d8ddcbe46" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="ff10a8d5-eb4b-4659-96fd-641162cb6304"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="ec4a6bf5-3a9d-4862-8266-9315e2f30817"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="682418e9-8bd4-4ae0-aa17-97df828bfd5c" type="7004">
      <children xmi:type="notation:Node" xmi:id="_qQxuwMUZEeqlFMxK4WGtuA" type="3004">
        <element xmi:type="proc:MetaDataLink" href="../../Launch%20a%20Delivery.proc#c3feb8dd-3403-47a9-8099-6d8dd986f937?fileId=_ytsfwME_Eeq6L8zfnBksuA$type=proc?"/>
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qQxuwcUZEeqlFMxK4WGtuA"/>
      </children>
      <styles xmi:type="notation:DrawerStyle" xmi:id="94084a5d-dd68-4b31-8b6b-d6303dbe8ca5"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="0a5108fa-db7b-484a-af71-e438c805a360"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="f9ff19c8-4c8d-45ff-8aef-b5904a4d67e9"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="ddeea049-2a86-4057-bbbc-454c89852d4b" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="../../Launch%20a%20Delivery.proc#_ytsf18E_Eeq6L8zfnBksuA?fileId=_ytsfwME_Eeq6L8zfnBksuA$type=proc$name=get%20Errors?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="f1bd752d-55dd-42e3-a378-15cf5cd2b219" x="48" y="438"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="4680ebd9-1d74-4575-ab9c-3509dc1d497b"/>
  <element xmi:type="proc:ActionProcess" href="../../Launch%20a%20Delivery.proc#_ytsfwME_Eeq6L8zfnBksuA?fileId=_ytsfwME_Eeq6L8zfnBksuA$type=proc$name=Launch%20a%20Delivery?"/>
</notation:Diagram>
]]></diagram>
</proc:process>