<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_8A4lQRs-EeaSVI_PvVjHMg">
  <metaDataLink id="_8A4lQxs-EeaSVI_PvVjHMg" output="true" name="creche" target="../00_Metadata/XML_etatDemande.md#_vLzhmRqAEeaSVI_PvVjHMg?fileId=_nDsK8BqAEeaSVI_PvVjHMg$type=md$name=creche?"/>
  <parameter id="_8A4lRBs-EeaSVI_PvVjHMg" input="true" name="id_demande" type="Integer" value="1"/>
  <parameter id="_8A4lRRs-EeaSVI_PvVjHMg" input="true" name="email_demandeur" type="String" value="jm.souchard@gmail.com"/>
  <actionProcessRef id="_IpP-gBtAEeaSVI_PvVjHMg" isBeginAction="false" name="getXMLDemande" nbCycles="-1" toleratedError="false" processMap="true" targetName="getXMLDemande.map#_W8jlEBkcEeaSVI_PvVjHMg?fileId=_W8jlEBkcEeaSVI_PvVjHMg$name=getXMLDemande$type=map?"/>
</proc:process>