DROP SCHEMA PIVOT_COLUMN IF EXISTS CASCADE;
CREATE SCHEMA PIVOT_COLUMN;
CREATE TABLE  PIVOT_COLUMN.PARAM_COL
(COLUMN_NAME  VARCHAR(30) NOT NULL,
 PIVOT_COL    BOOLEAN,
 CONSTRAINT   PK_PARAM_COL PRIMARY KEY (COLUMN_NAME));

INSERT INTO   PIVOT_COLUMN.PARAM_COL VALUES ('ID_CUSTOMER',true);
INSERT INTO   PIVOT_COLUMN.PARAM_COL VALUES ('LASTNAME',true);
INSERT INTO   PIVOT_COLUMN.PARAM_COL VALUES ('FIRSTNAME',false);
INSERT INTO   PIVOT_COLUMN.PARAM_COL VALUES ('MOBILE',true);
INSERT INTO   PIVOT_COLUMN.PARAM_COL VALUES ('EMAIL',true);
INSERT INTO   PIVOT_COLUMN.PARAM_COL VALUES ('BIRTHDATE',true);

CREATE TABLE  PIVOT_COLUMN.ENTRANCE_TABLE 
(ID_REF       INTEGER NOT NULL,
 ID_CUSTOMER  INTEGER,
 LASTNAME     VARCHAR(50),
 FIRSTNAME    VARCHAR(50),
 MOBILE       VARCHAR(20),
 EMAIL        VARCHAR(100),
 BIRTHDATE    TIMESTAMP,
 CONSTRAINT   PK_ENTRANCE_TABLE PRIMARY KEY (ID_REF));
 
INSERT INTO   PIVOT_COLUMN.ENTRANCE_TABLE VALUES (1,1020,'Victory','Jeanne',NULL,'j.victory@gmail.com',current_timestamp - 30 year);
INSERT INTO   PIVOT_COLUMN.ENTRANCE_TABLE VALUES (2,2010,'Trafalgar','Charles','0102030405','c.trafalgar@gmail.com',current_timestamp - 20 year);  
INSERT INTO   PIVOT_COLUMN.ENTRANCE_TABLE VALUES (3,2320,'Waterloo','Baudoin','0504030201',NULL,current_timestamp - 50 year);

CREATE TABLE  PIVOT_COLUMN.TARGET_TABLE
(ID_REF       INTEGER NOT NULL,
 COLUMN_NAME  VARCHAR(30) NOT NULL,
 COLUMN_VALUE VARCHAR(100),
 CONSTRAINT   PK_TARGET_TABLE PRIMARY KEY (ID_REF,COLUMN_NAME));