<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="28ebef3c-6c63-407d-8e9f-efec344489bb">
  <metaDataLink id="92e56676-6f2d-4218-bd91-8f37891768d1" output="true" name="customerDetails" target="resource.md#_2nAbjZmgEeyjqJcu_tQBzg?fileId=_2nAbgJmgEeyjqJcu_tQBzg$type=md$name=customerDetails?"/>
  <parameter id="319db0e3-e4a0-4801-ad9b-e09970e57c59" input="true" name="cus_id" type="Integer" value="10"/>
  <actionProcessRef id="3363e1ce-25b6-47ab-9b2b-2ee3924a1735" isBeginAction="false" name="Generate xml customerDetails WS" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_q6vBwZmgEeyjqJcu_tQBzg?fileId=_q6vBwZmgEeyjqJcu_tQBzg$name=Generate%20xml%20customerDetails%20WS$type=map?"/>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=28ebef3c-6c63-407d-8e9f-efec344489bb?" xmi:id="_cPnJoJmjEeyjqJcu_tQBzg" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_cwbXsJmjEeyjqJcu_tQBzg" type="2003">
    <children xmi:type="notation:Node" xmi:id="_cwdz8JmjEeyjqJcu_tQBzg" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_cwdz8ZmjEeyjqJcu_tQBzg" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_cwdz8pmjEeyjqJcu_tQBzg" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_cwdz85mjEeyjqJcu_tQBzg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_cwdz9JmjEeyjqJcu_tQBzg"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_cwebAJmjEeyjqJcu_tQBzg" type="7004">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_cwebAZmjEeyjqJcu_tQBzg"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_cwebApmjEeyjqJcu_tQBzg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_cwebA5mjEeyjqJcu_tQBzg"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_cwbXsZmjEeyjqJcu_tQBzg" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#3363e1ce-25b6-47ab-9b2b-2ee3924a1735?fileId=28ebef3c-6c63-407d-8e9f-efec344489bb$type=proc$name=Generate%20xml%20customerDetails%20WS?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cwbXspmjEeyjqJcu_tQBzg" x="382" y="96"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_fL8X4JmjEeyjqJcu_tQBzg" type="2006">
    <children xmi:type="notation:Node" xmi:id="_fL-NEJmjEeyjqJcu_tQBzg" type="5006"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_fL8X4ZmjEeyjqJcu_tQBzg" fontName="Segoe UI"/>
    <element xmi:type="proc:MetaDataLink" href="resource.proc#92e56676-6f2d-4218-bd91-8f37891768d1?fileId=28ebef3c-6c63-407d-8e9f-efec344489bb$type=proc?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fL8X4pmjEeyjqJcu_tQBzg" x="732" y="95"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_gc3NMJmjEeyjqJcu_tQBzg" type="2005">
    <children xmi:type="notation:Node" xmi:id="_gc5pcJmjEeyjqJcu_tQBzg" type="5005"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_gc30QJmjEeyjqJcu_tQBzg" fontName="Segoe UI"/>
    <element xmi:type="proc:Parameter" href="resource.proc#319db0e3-e4a0-4801-ad9b-e09970e57c59?fileId=28ebef3c-6c63-407d-8e9f-efec344489bb$type=proc$name=cus_id?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gc30QZmjEeyjqJcu_tQBzg" x="115" y="90"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_cPnJoZmjEeyjqJcu_tQBzg"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#28ebef3c-6c63-407d-8e9f-efec344489bb?fileId=28ebef3c-6c63-407d-8e9f-efec344489bb$type=proc$name=getXmlCustomerDetailsWS?"/>
</notation:Diagram>
]]></diagram>
</proc:process>