<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="174870dd-3036-4e1e-ad78-2643f3eeef91">
  <metaDataLink id="fd25859f-28b1-4770-91a5-505499896957" output="true" name="customerDetails" target="resource.md#_AMYXCDT0Ee2K1spis4bODw?fileId=_AMXv8DT0Ee2K1spis4bODw$type=md$name=customerDetails?"/>
  <parameter id="b5fa513a-6b5d-4e49-9826-a5e8dbab53fb" input="true" name="cus_id" type="Integer" value="10"/>
  <actionProcessRef id="bbbac3cb-1894-4aed-ab68-fbf85cc546d3" isBeginAction="false" name="GenerateXMLCustomerDetails_WS" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_auDGkDTuEe2K1spis4bODw?fileId=_auDGkDTuEe2K1spis4bODw$name=GenerateXMLCustomerDetails_WS$type=map?"/>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=174870dd-3036-4e1e-ad78-2643f3eeef91?" xmi:id="_n-uDsDT0Ee2K1spis4bODw" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_dG6hwDT2Ee2K1spis4bODw" type="2005">
    <children xmi:type="notation:Node" xmi:id="_dG9lEDT2Ee2K1spis4bODw" type="5005"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_dG6hwTT2Ee2K1spis4bODw" fontName="Segoe UI"/>
    <element xmi:type="proc:Parameter" href="resource.proc#b5fa513a-6b5d-4e49-9826-a5e8dbab53fb?fileId=174870dd-3036-4e1e-ad78-2643f3eeef91$type=proc$name=cus_id?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dG6hwjT2Ee2K1spis4bODw" x="492" y="132"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_u9jzMDT2Ee2K1spis4bODw" type="2006">
    <children xmi:type="notation:Node" xmi:id="_u9ndkDT2Ee2K1spis4bODw" type="5006"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_u9jzMTT2Ee2K1spis4bODw" fontName="Segoe UI"/>
    <element xmi:type="proc:MetaDataLink" href="resource.proc#fd25859f-28b1-4770-91a5-505499896957?fileId=174870dd-3036-4e1e-ad78-2643f3eeef91$type=proc?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_u9jzMjT2Ee2K1spis4bODw" x="636" y="132"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_5M5VADT2Ee2K1spis4bODw" type="2003">
    <children xmi:type="notation:Node" xmi:id="_5M7KMDT2Ee2K1spis4bODw" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_5M7KMTT2Ee2K1spis4bODw" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_5M7KMjT2Ee2K1spis4bODw" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_5M7KMzT2Ee2K1spis4bODw"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_5M7KNDT2Ee2K1spis4bODw"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_5M7KNTT2Ee2K1spis4bODw" type="7004">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_5M7KNjT2Ee2K1spis4bODw"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_5M7KNzT2Ee2K1spis4bODw"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_5M7KODT2Ee2K1spis4bODw"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_5M5VATT2Ee2K1spis4bODw" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#bbbac3cb-1894-4aed-ab68-fbf85cc546d3?fileId=174870dd-3036-4e1e-ad78-2643f3eeef91$type=proc$name=GenerateXMLCustomerDetails_WS?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5M5VAjT2Ee2K1spis4bODw" x="504" y="204"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_n-uDsTT0Ee2K1spis4bODw"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#174870dd-3036-4e1e-ad78-2643f3eeef91?fileId=174870dd-3036-4e1e-ad78-2643f3eeef91$type=proc$name=getXmlCustomerDetails?"/>
</notation:Diagram>
]]></diagram>
</proc:process>