<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="11707c4f-9911-4151-881f-b178061ec5fe">
  <metaDataLink id="b6218459-01de-421c-9ca0-61d34105dcde" output="true" name="CustomerDetails" target="resource.md#_uf4NEZmEEeyjqJcu_tQBzg?fileId=_uf4NEJmEEeyjqJcu_tQBzg$type=md$name=CustomerDetails?"/>
  <parameter id="2ef88a72-d7fa-400a-a77b-930a68d59e3f" input="true" name="cus_id" type="Integer" value="10"/>
  <actionProcessRef id="499f8098-f8d4-4a0e-81e9-eede4d960bee" isBeginAction="false" name="Generate json customerDetails WS" nbCycles="-1" toleratedError="false" processMap="true" targetName="resource.map#_nPV-sJmEEeyjqJcu_tQBzg?fileId=_nPV-sJmEEeyjqJcu_tQBzg$name=Generate%20json%20customerDetails%20WS$type=map?"/>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.3/notation#/?fileId=11707c4f-9911-4151-881f-b178061ec5fe?" xmi:id="_-anLcJmEEeyjqJcu_tQBzg" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_AR6EQJmFEeyjqJcu_tQBzg" type="2003">
    <children xmi:type="notation:Node" xmi:id="_AR7SYJmFEeyjqJcu_tQBzg" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="_AR7SYZmFEeyjqJcu_tQBzg" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_AR7SYpmFEeyjqJcu_tQBzg" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_AR7SY5mFEeyjqJcu_tQBzg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_AR7SZJmFEeyjqJcu_tQBzg"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_AR7SZZmFEeyjqJcu_tQBzg" type="7004">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_AR7SZpmFEeyjqJcu_tQBzg"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_AR7SZ5mFEeyjqJcu_tQBzg"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_AR7SaJmFEeyjqJcu_tQBzg"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_AR6EQZmFEeyjqJcu_tQBzg" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="resource.proc#499f8098-f8d4-4a0e-81e9-eede4d960bee?fileId=11707c4f-9911-4151-881f-b178061ec5fe$type=proc$name=Generate%20json%20customerDetails%20WS?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AR6EQpmFEeyjqJcu_tQBzg" x="304" y="154"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_BSSjMJmFEeyjqJcu_tQBzg" type="2006">
    <children xmi:type="notation:Node" xmi:id="_BSTxUJmFEeyjqJcu_tQBzg" type="5006"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_BSSjMZmFEeyjqJcu_tQBzg" fontName="Segoe UI"/>
    <element xmi:type="proc:MetaDataLink" href="resource.proc#b6218459-01de-421c-9ca0-61d34105dcde?fileId=11707c4f-9911-4151-881f-b178061ec5fe$type=proc?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BSSjMpmFEeyjqJcu_tQBzg" x="660" y="124"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_C4vjoJmFEeyjqJcu_tQBzg" type="2005">
    <children xmi:type="notation:Node" xmi:id="_C4wxwJmFEeyjqJcu_tQBzg" type="5005"/>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_C4vjoZmFEeyjqJcu_tQBzg" fontName="Segoe UI"/>
    <element xmi:type="proc:Parameter" href="resource.proc#2ef88a72-d7fa-400a-a77b-930a68d59e3f?fileId=11707c4f-9911-4151-881f-b178061ec5fe$type=proc$name=cus_id?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C4vjopmFEeyjqJcu_tQBzg" x="123" y="117"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_-anLcZmEEeyjqJcu_tQBzg"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#11707c4f-9911-4151-881f-b178061ec5fe?fileId=11707c4f-9911-4151-881f-b178061ec5fe$type=proc$name=Generate%20customerDetails_openApiV2?"/>
</notation:Diagram>
]]></diagram>
</proc:process>