DROP SCHEMA HUMAN_RESOURCE IF EXISTS CASCADE;
CREATE SCHEMA HUMAN_RESOURCE;

CREATE TABLE COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE (MATRICULE_NUMBER CHAR(3) NOT NULL,FIRSTNAME VARCHAR(100),LASTNAME VARCHAR(100),SUPERVISOR_MATRICULE_NUMBER CHAR(3),CONSTRAINT PK_HEADQUARTER_EMPLOYEE PRIMARY KEY (MATRICULE_NUMBER))
CREATE TABLE COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE_HIERARCHY (MATRICULE_NUMBER CHAR(3) NOT NULL,FIRSTNAME VARCHAR(100),LASTNAME VARCHAR(100),SUPERVISOR_MATRICULE_NUMBER CHAR(3),HIERARCHY_LEVEL INTEGER,SUPERVISOR_NAME VARCHAR(100),DIRECTOR_NAME VARCHAR(100),HIERARCHY_NAME VARCHAR(500),HIERARCHY_MATRICULE_NUMBER VARCHAR(100),CONSTRAINT PK_HEADQUARTER_EMPLOYEE_HIERARCHY PRIMARY KEY (MATRICULE_NUMBER))

INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('001','Ken','Sanchez','000')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('002','David','Bradley','001')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('003','Dave','King','001')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('004','Brian','Welcker','001')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('005','Jordan','King','003')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('006','Jane','Smith','004')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('007','John','Baker','005')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('008','Jonathan','Smile','005')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('009','Carol','Philips','004')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('010','Jess','Maurith','000')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('011','Ted','Mc Donald','010')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('012','James','Gordon','011')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('013','Ruth','Beth','011')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('014','Fiz','Storm','011')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('015','Sophie','Finch','010')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('016','Alicia','Fowley','015')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('017','Beth','Capice','015')
INSERT INTO COMPANY_ACTIVITY.HEADQUARTER_EMPLOYEE VALUES ('018','Betty','Strimp','015')


