Create table FTP_PARAMS
(	
	"NAME" VARCHAR2(50 CHAR) NOT NULL,
	"CONTEXT" VARCHAR2(50 CHAR) NOT NULL,
	"ACTIVE" CHAR(1 CHAR) NOT NULL,
	"TYPE" VARCHAR2(10 CHAR) NOT NULL,
	"PORT" VARCHAR2(6 CHAR) NOT NULL,
	"PASSIVE_MODE" CHAR(1 CHAR) NOT NULL,
	"FTP_PASSIVE" CHAR(1 CHAR) NOT NULL,
	"HOST" VARCHAR2(100 CHAR) NOT NULL,
	"USERNAME" VARCHAR2(50 CHAR) NULL,
	"PASSWORD" VARCHAR2(50 CHAR) NULL,
	"DIR_OUT" VARCHAR2(150 CHAR) NULL,
	"DIR_IN" VARCHAR2(150 CHAR) NULL
	, CONSTRAINT TEC_FTP_PARAMS_PK PRIMARY KEY (NAME,CONTEXT)
	
)

INSERT INTO "FTP_PARAMS" (NAME, CONTEXT, ACTIVE, TYPE, PORT, FTP_PASSIVE, HOST, USERNAME, PASSWORD, DIR_OUT, DIR_IN) 
VALUES ('MYFTP', 'DEVL', 'Y', 'FTP', '21', 'N', 'ftp.server.com', 'user', 'password', 'Directory/Out/', 'Directory/In/')
