<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_evZFcOKTEeiIZrZhxxfAyA">
  <actionProcessRef id="_Km6iAOKYEeiIZrZhxxfAyA" isBeginAction="false" name="REPLICATOR Rdbms.tp" nbCycles="-1" repetitionQuery="$Multiple_Files_Folder_for_Replic/file" repetitionVariableName="SOURCE" toleratedError="false" targetName="../global/templates.generic/Replication/REPLICATOR%20Rdbms.tp.proc#_zZDewaLZEd6qz86y5ipz-A?fileId=_zZDewaLZEd6qz86y5ipz-A$type=proc$name=REPLICATOR%20Rdbms.tp?">
    <metaDataLink id="_VuDOgOKYEeiIZrZhxxfAyA" name="TARGET" target="20-Metadata/HSQL_Datamart.md#_uk-6wNjzEeiHBZdKZ0VXqw?fileId=_uk-T8tjzEeiHBZdKZ0VXqw$type=md$name=LOAD_FILES?"/>
    <metaDataLink id="_yP0l4OKYEeiIZrZhxxfAyA" name="Multiple_Files_Folder_for_Replic" target="20-Metadata/FILE_Server.md#_q2foEeKYEeiIZrZhxxfAyA?fileId=_exiQINjzEeiHBZdKZ0VXqw$type=md$name=Multiple_Files_Folder_for_Replic?"/>
    <parameter id="_YFaugOKYEeiIZrZhxxfAyA" name="createTables" type="Boolean" value="true"/>
    <parameter id="_YLln8OKYEeiIZrZhxxfAyA" name="dropTables" type="Boolean" value="true"/>
    <parameter id="_YfZUwOKYEeiIZrZhxxfAyA" name="dropPk" type="Boolean" value="true"/>
    <parameter id="_YpRCcOKYEeiIZrZhxxfAyA" name="createPk" type="Boolean" value="true"/>
    <parameter id="_Yv_VgOKYEeiIZrZhxxfAyA" name="createFk" type="Boolean" value="true"/>
    <parameter id="_ZHJ4UOKYEeiIZrZhxxfAyA" name="loadData" type="String" value="true"/>
    <parameter id="_iIumgOKYEeiIZrZhxxfAyA" name="query" type="String" value="$SOURCE"/>
  </actionProcessRef>
</proc:process>