<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_ytqDgME_Eeq6L8zfnBksuA">
  <actionProcessRef id="_ytqDhME_Eeq6L8zfnBksuA" generationCondition="" isBeginAction="false" name="Recreate constraints" nbCycles="-1" toleratedError="false" targetName="platform:/plugin/com.indy.environment/templates/templates.generic/Automation/AUTOMATION%20Rdbms%20Operations.tp.proc#_sknoQ6x2Ed6xTOAeaNjskA?fileId=_sknoQ6x2Ed6xTOAeaNjskA$type=proc$name=AUTOMATION%20Rdbms%20Operations.tp?">
    <metaDataLink id="_ytqDhsE_Eeq6L8zfnBksuA" name="SOURCE" target="../20-Metadata/HSQL_Datamart.md#_yslFesE_Eeq6L8zfnBksuA?fileId=_yskeYME_Eeq6L8zfnBksuA$type=md$name=HOTEL_DATAMART?"/>
    <parameter id="_ytqDh8E_Eeq6L8zfnBksuA" name="createFk" type="Boolean" value="true"/>
  </actionProcessRef>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.2/notation#/?fileId=_ytqDgME_Eeq6L8zfnBksuA?" xmi:id="b48554ce-eca1-42a4-afae-2bf645506279" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="97685714-5a97-4204-84f0-dfcceca63fc3" type="2003">
    <children xmi:type="notation:Node" xmi:id="8f14dfb4-8514-48ab-98ac-84b667692862" type="5003"/>
    <children xmi:type="notation:Node" xmi:id="c253e56c-6fed-4d94-ad50-a1b34dac320f" type="7003">
      <styles xmi:type="notation:DrawerStyle" xmi:id="9b5bed4a-1be1-468e-8908-40fddcbcb04b" collapsed="true"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="aafdf68b-e518-460f-887a-f479d14e37df"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="5a305b7e-005f-4537-8b5b-280ec82f8c92"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="6de2ccab-aa60-4057-94e5-ff7b75583b67" type="7004">
      <children xmi:type="notation:Node" xmi:id="2194a633-852d-46b5-bbca-47356362587f" type="3004">
        <element xmi:type="proc:MetaDataLink" href="../../Terminate%20LOAD_ALL_DATAMART.proc#_ytqDhsE_Eeq6L8zfnBksuA?fileId=_ytqDgME_Eeq6L8zfnBksuA$type=proc?"/>
        <layoutConstraint xmi:type="notation:Location" xmi:id="72cce28d-ae53-41e3-a3bd-2b4d7f26b44c"/>
      </children>
      <styles xmi:type="notation:DrawerStyle" xmi:id="5b7bee04-075f-4ca0-b080-d1827d6d966f"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="e02913c1-2a05-4567-b90f-d8c8a229c67b"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="bc8d92bc-0827-4a6a-a691-d680457b894e"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="42cb8ac4-a2b6-47d2-a6f3-32744a46e15b" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionProcessRef" href="../../Terminate%20LOAD_ALL_DATAMART.proc#_ytqDhME_Eeq6L8zfnBksuA?fileId=_ytqDgME_Eeq6L8zfnBksuA$type=proc$name=Recreate%20constraints?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="f7b301a8-b53d-4b95-83e3-54f2cee1c691" x="30" y="30"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="2e46de69-af2c-4401-ac7c-eb81786de187"/>
  <element xmi:type="proc:ActionProcess" href="../../Terminate%20LOAD_ALL_DATAMART.proc#_ytqDgME_Eeq6L8zfnBksuA?fileId=_ytqDgME_Eeq6L8zfnBksuA$type=proc$name=Terminate%20LOAD_ALL_DATAMART?"/>
</notation:Diagram>
]]></diagram>
</proc:process>