<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_pnHdIdj0EeiHBZdKZ0VXqw">
  <actionCode id="_KIHQ4Nj6EeiHBZdKZ0VXqw" isBeginAction="false" name="FileWait" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.FileWaitActionCodeI">
    <link id="_71EzoNj6EeiHBZdKZ0VXqw" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_2LsJQNj6EeiHBZdKZ0VXqw"/>
    <metaDataLink id="_KIMJYNj6EeiHBZdKZ0VXqw" name="Multiple_Files_Folder" target="../20-Metadata/FILE_Server.md#_e7FNsNjzEeiHBZdKZ0VXqw?fileId=_exiQINjzEeiHBZdKZ0VXqw$type=md$name=Multiple_Files_Folder?"/>
    <metaDataLink id="_Ot6XUNj6EeiHBZdKZ0VXqw" name="LOAD_FILES" target="../20-Metadata/HSQL_Datamart.md#_uk-6wNjzEeiHBZdKZ0VXqw?fileId=_uk-T8tjzEeiHBZdKZ0VXqw$type=md$name=LOAD_FILES?"/>
    <parameter id="_K4e94Nj6EeiHBZdKZ0VXqw" name="WAIT_FILE_INCLUDES" type="String" value="*.txt"/>
    <parameter id="_MByIQNj6EeiHBZdKZ0VXqw" name="WAIT_FILE_NB_FILES" type="Integer" value="-1"/>
  </actionCode>
  <actionCode id="_2LsJQNj6EeiHBZdKZ0VXqw" isBeginAction="false" name="SqlOperation" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JdbcActionCodeI">
    <bindLink id="_D1BswNj7EeiHBZdKZ0VXqw" bindType="DirectBind" targetId="_DbmgINj7EeiHBZdKZ0VXqw"/>
    <metaDataLink id="_2Ly28Nj6EeiHBZdKZ0VXqw" name="IND_SESSION_FILE_OP_LST" target="../20-Metadata/HSQL_Datamart.md#_a79Bgdj6EeiHBZdKZ0VXqw?fileId=_uk-T8tjzEeiHBZdKZ0VXqw$type=md$name=IND_SESSION_FILE_OP_LST?"/>
    <parameter id="_2Ly28dj6EeiHBZdKZ0VXqw" name="SQL_ACTION_TYPE" type="String" value="SELECT"/>
    <parameter id="_-_m18Nj6EeiHBZdKZ0VXqw" name="SQL_ACTION_TYPE_STAT" type="String" value="SELECT"/>
    <code>SELECT FILE_NAME,&#xD;
	   SUBSTR(FILE_NAME,6,8) AS FILE_DATE &#xD;
FROM   LOAD_FILES.IND_SESSION_FILE_OP_LST&#xD;
WHERE  SESS_ID='${/CORE_SESSION_ID}$'</code>
  </actionCode>
  <actionCode id="_DbmgINj7EeiHBZdKZ0VXqw" isBeginAction="false" name="ExecuteDelivery" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.ExecDeliveryActionCodeI">
    <parameter id="_L3XLgNj7EeiHBZdKZ0VXqw" name="p_file_name" type="String" value=":{FILE_NAME}:"/>
    <parameter id="_OfOloNj7EeiHBZdKZ0VXqw" name="p_file_date" type="String" value=":{FILE_DATE}:"/>
    <parameter id="_SJOyMNj7EeiHBZdKZ0VXqw" name="DELIV_NAME" type="String" value="Mapping with Wait files and SQL Operation"/>
    <parameter id="_SloaUNj7EeiHBZdKZ0VXqw" name="DELIV_SESSION_NAME" type="String" value="File treatment of :{FILE_NAME}: with :{FILE_DATE}:"/>
  </actionCode>
</proc:process>