CREATE SCHEMA ODS;

CREATE SCHEMA WORK;
CREATE TABLE ODS.ODS_BANISHED_CUSTOMER
(	
	ID_BAN_CUSTOMER INTEGER NOT NULL
	, CONSTRAINT PK_BANISHED_CUSTOMER PRIMARY KEY (ID_BAN_CUSTOMER)
);
CREATE TABLE ODS.ODS_CUSTOMER
(	
	ID_CUSTOMER INTEGER NOT NULL
	, CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID_CUSTOMER)
);

INSERT INTO ODS.ODS_BANISHED_CUSTOMER 
SELECT GEN_ID 
FROM   UNNEST(SEQUENCE_ARRAY(50, 99, 1)) AS GENERATE_SERIES(GEN_ID);