<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="_tkgoARtOEeaSVI_PvVjHMg">
  <parameter id="_tkgoAhtOEeaSVI_PvVjHMg" input="true" output="false" name="id_inscription" type="Integer" value="1"/>
  <parameter id="_tkgoAxtOEeaSVI_PvVjHMg" output="true" name="inscription_supprimee" type="Boolean" value="true"/>
  <actionCode id="_tkgoBBtOEeaSVI_PvVjHMg" isBeginAction="false" name="SqlOperation DELETE" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JdbcActionCodeI">
    <link id="_tkgoBRtOEeaSVI_PvVjHMg" executionType="OK" generationType="OK_KO" mandatory="1" targetId="_tkgoCRtOEeaSVI_PvVjHMg"/>
    <metaDataLink id="_z9JlEBtOEeaSVI_PvVjHMg" name="INSCRIPTION" target="../00_Metadata/HSQL_Creche.md#_aTLMcRd4Eeag17CW0UpctQ?fileId=_JZOm4BdDEeasp6ebq_qPSQ$type=md$name=INSCRIPTION?"/>
    <parameter id="_tkgoBxtOEeaSVI_PvVjHMg" name="SQL_ACTION_TYPE" type="String" value="DDL_DML"/>
    <parameter id="_tkgoCBtOEeaSVI_PvVjHMg" name="SQL_CONNECTION" type="String"/>
    <code>DELETE FROM VILLEURBANNE.INSCRIPTION&#xD;
WHERE  ID_INSCRIPTION=${~/id_inscription}$</code>
  </actionCode>
  <actionCode id="_tkgoCRtOEeaSVI_PvVjHMg" isBeginAction="false" name="Sql To Parameters" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.sqlToParameters">
    <metaDataLink id="_otAmMBtREeaSVI_PvVjHMg" name="VILLEURBANNE" target="../00_Metadata/HSQL_Creche.md#_w4eFsBd1Eeag17CW0UpctQ?fileId=_JZOm4BdDEeasp6ebq_qPSQ$type=md$name=VILLEURBANNE?"/>
    <code>&lt;sqlToParameters>&#xD;
&lt;parameter name=&quot;~/inscription_supprimee&quot; type=&quot;Boolean&quot;>&#xD;
SELECT 'true' AS inscription_supprimee&#xD;
FROM   (VALUES(0))&#xD;
&lt;/parameter>&#xD;
&lt;/sqlToParameters> </code>
  </actionCode>
</proc:process>