DROP SCHEMA CNY_ACTIVITY IF EXISTS CASCADE;
CREATE SCHEMA CNY_ACTIVITY;
CREATE TABLE CNY_ACTIVITY.ACTIVITY (	
	EMP_NO INTEGER NOT NULL,ACT_MONTH INT NOT NULL,ACT_YEAR INT NOT NULL,
	CODE_ID01 CHAR(2),CODE_ID02 CHAR(2),CODE_ID03 CHAR(2),CODE_ID04 CHAR(2),
	CODE_ID05 CHAR(2),CODE_ID06 CHAR(2),CODE_ID07 CHAR(2),CODE_ID08 CHAR(2),
	CODE_ID09 CHAR(2),CODE_ID10 CHAR(2),CODE_ID11 CHAR(2),CODE_ID12 CHAR(2),
	CODE_ID13 CHAR(2),CODE_ID14 CHAR(2),CODE_ID15 CHAR(2),CODE_ID16 CHAR(2),
	CODE_ID17 CHAR(2),CODE_ID18 CHAR(2),CODE_ID19 CHAR(2),CODE_ID20 CHAR(2),
	CODE_ID21 CHAR(2),CODE_ID22 CHAR(2),CODE_ID23 CHAR(2),CODE_ID24 CHAR(2),
	CODE_ID25 CHAR(2),CODE_ID26 CHAR(2),CODE_ID27 CHAR(2),CODE_ID28 CHAR(2),
	CODE_ID29 CHAR(2),CODE_ID30 CHAR(2),CODE_ID31 CHAR(2), 
	CONSTRAINT PK_ACTIVITY PRIMARY KEY (EMP_NO,ACT_MONTH,ACT_YEAR));
CREATE TABLE CNY_ACTIVITY.EMPLOYE (   
    EMP_NO INT NOT NULL,EMP_FIRST_NAME VARCHAR(50),EMP_LAST_NAME VARCHAR(50),
    CONSTRAINT PK_EMPLOYE PRIMARY KEY (EMP_NO));
CREATE TABLE CNY_ACTIVITY.DETAILLED_ACT (	
	EMP_NO INTEGER NOT NULL,ACTIVITY_DATE TIMESTAMP NOT NULL,
	FIRSTNAME VARCHAR(100),LASTNAME VARCHAR(100),ACTIVITY_CODE CHAR(2) NOT NULL,
	CONSTRAINT PK_DETAILLED_ACT PRIMARY KEY (EMP_NO,ACTIVITY_DATE));
	
INSERT INTO CNY_ACTIVITY.EMPLOYE VALUES (1,'John','SMITH');
INSERT INTO CNY_ACTIVITY.EMPLOYE VALUES (2,'Joe','KELLY');
INSERT INTO CNY_ACTIVITY.EMPLOYE VALUES (3,'Melinda','PALMER');

INSERT INTO CNY_ACTIVITY.ACTIVITY (EMP_NO,ACT_MONTH,ACT_YEAR,CODE_ID04,CODE_ID06)
VALUES (1,3,2017,'CO','AB');
INSERT INTO CNY_ACTIVITY.ACTIVITY (EMP_NO,ACT_MONTH,ACT_YEAR,CODE_ID01,CODE_ID03,CODE_ID07)
VALUES (2,3,2017,'AB','MA','CO');
INSERT INTO CNY_ACTIVITY.ACTIVITY (EMP_NO,ACT_MONTH,ACT_YEAR,CODE_ID02,CODE_ID05,CODE_ID08,CODE_ID09,CODE_ID10)
VALUES (3,3,2017,'AB','MA','CO','CO','CO');


