<?xml version="1.0" encoding="UTF-8"?>
<proc:process xmlns:proc="http://www.example.org/proc" id="01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4">
  <actionCode id="96495053-f66b-4d06-96d0-9d8ff06585f6" isBeginAction="false" name="start1" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
    <link id="2730bb34-a403-4d16-930a-a50f20861ecc" executionType="OK" generationType="OK_KO" mandatory="0" targetId="915d97c4-04b0-48ac-8152-0e57bd5d2812"/>
  </actionCode>
  <actionCode id="915d97c4-04b0-48ac-8152-0e57bd5d2812" isBeginAction="false" name="loop1" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
    <link id="04814dd4-94a5-43c8-bc83-f2f0f1f58c55" executionCondition="${./loop1/CORE_NB_EXECUTIONS}$ &lt;= 3" executionType="OK" generationType="OK_KO" mandatory="1" targetId="204b76c5-9cf6-4784-8d98-2fa965021fbd"/>
    <link id="c3e2ccb6-6c58-439b-9c24-7265b6246375" executionCondition="${./loop1/CORE_NB_EXECUTIONS}$ > 3" executionType="OK" generationType="OK_KO" mandatory="1" targetId="ebc308bc-a746-496e-9862-7cffa5ad3b57"/>
  </actionCode>
  <actionCode id="204b76c5-9cf6-4784-8d98-2fa965021fbd" isBeginAction="false" name="sleep11" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JSleepActionCodeI">
    <link id="2a44fb7e-6f3c-4d47-aba6-5357ec6d8741" executionType="OK" generationType="OK_KO" mandatory="1" targetId="788ceec3-b95b-42a4-8ba9-23fc4376dcd4"/>
  </actionCode>
  <actionCode id="788ceec3-b95b-42a4-8ba9-23fc4376dcd4" isBeginAction="false" name="sleep12" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JSleepActionCodeI">
    <link id="dd32e714-5c8b-4fba-8662-e8a32fd3a4c9" executionType="OK" generationType="OK_KO" mandatory="0" targetId="915d97c4-04b0-48ac-8152-0e57bd5d2812"/>
  </actionCode>
  <actionCode id="ebc308bc-a746-496e-9862-7cffa5ad3b57" isBeginAction="false" name="end1" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI"/>
  <actionCode id="2bfdc822-9ce6-404c-84f3-14fcac817e10" isBeginAction="false" name="end2" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI"/>
  <actionCode id="70028f95-769c-4c44-8695-a1c885629e0e" isBeginAction="false" name="sleep22" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JSleepActionCodeI">
    <link id="413c5ef6-398d-4da2-979a-268ba22416c5" executionType="OK" generationType="OK_KO" mandatory="1" targetId="c00deb6b-d47e-4023-b976-dcc04f232fa9"/>
  </actionCode>
  <actionCode id="c00deb6b-d47e-4023-b976-dcc04f232fa9" isBeginAction="true" name="loop2" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.EmptyActionCodeI">
    <link id="38fe3442-aa8e-40ec-ab38-62b004ce1d43" executionCondition="${./loop2/CORE_NB_EXECUTIONS}$ &lt;= 3" executionType="OK" generationType="OK_KO" mandatory="1" targetId="5d97cfd2-4fa2-4a5b-9bc2-67002f8ef1e4"/>
    <link id="4397f238-8569-4b04-b37c-d276123bef9f" executionCondition="${./loop2/CORE_NB_EXECUTIONS}$ > 3" executionType="OK" generationType="OK_KO" mandatory="1" targetId="2bfdc822-9ce6-404c-84f3-14fcac817e10"/>
  </actionCode>
  <actionCode id="5d97cfd2-4fa2-4a5b-9bc2-67002f8ef1e4" isBeginAction="false" name="sleep21" nbCycles="-1" toleratedError="false" technology="com.indy.engine.actionCodes.JSleepActionCodeI">
    <link id="bc7f9440-dd96-419d-b5ed-ee3fc9a6424d" executionType="OK" generationType="OK_KO" mandatory="1" targetId="70028f95-769c-4c44-8695-a1c885629e0e"/>
  </actionCode>
  <diagram><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<notation:Diagram xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.1/notation" xmlns:proc="http://www.example.org/proc" xsi:schemaLocation="http://www.eclipse.org/gmf/runtime/1.0.1/notation http://www.eclipse.org/gmf/runtime/1.0.2/notation#/?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4?" xmi:id="_pzlR4Lk8EeuevZq3ZGZbnA" type="Proc" measurementUnit="Pixel">
  <children xmi:type="notation:Node" xmi:id="_rAOEILk8EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_rAP5ULk8EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_rAP5Ubk8EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_rAP5Urk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_rAP5U7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_rAP5VLk8EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_rAP5Vbk8EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_rAP5Vrk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_rAP5V7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_rAP5WLk8EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_rAOEIbk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#96495053-f66b-4d06-96d0-9d8ff06585f6?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=start1?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rAOEIrk8EeuevZq3ZGZbnA" x="30" y="30"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_sV9vELk8EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_sV-9MLk8EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_sV-9Mbk8EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_sV-9Mrk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_sV-9M7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_sV-9NLk8EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_sV-9Nbk8EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_sV-9Nrk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_sV-9N7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_sV-9OLk8EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_sV9vEbk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#915d97c4-04b0-48ac-8152-0e57bd5d2812?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=loop1?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sV9vErk8EeuevZq3ZGZbnA" x="90" y="132"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_tQh54Lk8EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_tQjvELk8EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_tQjvEbk8EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_tQjvErk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_tQjvE7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_tQjvFLk8EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_tQjvFbk8EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_tQjvFrk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_tQjvF7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_tQjvGLk8EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_tQh54bk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#204b76c5-9cf6-4784-8d98-2fa965021fbd?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=sleep11?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tQh54rk8EeuevZq3ZGZbnA" x="168" y="240"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_ua1J0Lk8EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_ua2X8Lk8EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_ua2X8bk8EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_ua2X8rk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_ua2X87k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_ua2X9Lk8EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ua2X9bk8EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_ua2X9rk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_ua2X97k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_ua2X-Lk8EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_ua1J0bk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#788ceec3-b95b-42a4-8ba9-23fc4376dcd4?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=sleep12?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ua1J0rk8EeuevZq3ZGZbnA" x="168" y="30"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_vggYcLk8EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_vghmkLk8EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_vghmkbk8EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_vghmkrk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_vghmk7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_vghmlLk8EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_vghmlbk8EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_vghmlrk8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_vghml7k8EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_vghmmLk8EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_vggYcbk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#ebc308bc-a746-496e-9862-7cffa5ad3b57?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=end1?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vggYcrk8EeuevZq3ZGZbnA" x="30" y="240"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_Ca0GULk9EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_Ca0GUbk9EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_Ca0GUrk9EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0GU7k9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0GVLk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0GVbk9EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Ca0GVrk9EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0GV7k9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0GWLk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0GWbk9EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_Ca0GWrk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#5d97cfd2-4fa2-4a5b-9bc2-67002f8ef1e4?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=sleep21?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ca0GW7k9EeuevZq3ZGZbnA" x="492" y="246"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_Ca0tZrk9EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_Ca0tZ7k9EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_Ca0taLk9EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0tabk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0tark9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0ta7k9EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Ca0tbLk9EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0tbbk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0tbrk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0tb7k9EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_Ca0tcLk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#2bfdc822-9ce6-404c-84f3-14fcac817e10?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=end2?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ca0tcbk9EeuevZq3ZGZbnA" x="354" y="246"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_Ca0thLk9EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_Ca0thbk9EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_Ca0thrk9EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0th7k9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0tiLk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0tibk9EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Ca0tirk9EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0ti7k9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0tjLk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0tjbk9EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_Ca0tjrk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#70028f95-769c-4c44-8695-a1c885629e0e?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=sleep22?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ca0tj7k9EeuevZq3ZGZbnA" x="492" y="36"/>
  </children>
  <children xmi:type="notation:Node" xmi:id="_Ca0tnLk9EeuevZq3ZGZbnA" type="2001">
    <children xmi:type="notation:Node" xmi:id="_Ca0tnbk9EeuevZq3ZGZbnA" type="5001"/>
    <children xmi:type="notation:Node" xmi:id="_Ca0tnrk9EeuevZq3ZGZbnA" type="7001">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0tn7k9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0toLk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0tobk9EeuevZq3ZGZbnA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_Ca0tork9EeuevZq3ZGZbnA" type="7002">
      <styles xmi:type="notation:DrawerStyle" xmi:id="_Ca0to7k9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:SortingStyle" xmi:id="_Ca0tpLk9EeuevZq3ZGZbnA"/>
      <styles xmi:type="notation:FilteringStyle" xmi:id="_Ca0tpbk9EeuevZq3ZGZbnA"/>
    </children>
    <styles xmi:type="notation:ShapeStyle" xmi:id="_Ca0tprk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:ActionCode" href="resource.proc#c00deb6b-d47e-4023-b976-dcc04f232fa9?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=loop2?"/>
    <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ca0tp7k9EeuevZq3ZGZbnA" x="414" y="138"/>
  </children>
  <styles xmi:type="notation:DiagramStyle" xmi:id="_pzlR4bk8EeuevZq3ZGZbnA"/>
  <element xmi:type="proc:ActionProcess" href="resource.proc#01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc$name=Loop?"/>
  <edges xmi:type="notation:Edge" xmi:id="_wQRogLk8EeuevZq3ZGZbnA" type="4001" source="_rAOEILk8EeuevZq3ZGZbnA" target="_sV9vELk8EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_wQRogbk8EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_wQRogrk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#2730bb34-a403-4d16-930a-a50f20861ecc?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wQRog7k8EeuevZq3ZGZbnA" points="[0, 0, -47, -60]$[47, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wQSPkLk8EeuevZq3ZGZbnA" id="(0.5,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yYIF07k8EeuevZq3ZGZbnA" id="(0.325,0.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_woG5sLk8EeuevZq3ZGZbnA" type="4001" source="_sV9vELk8EeuevZq3ZGZbnA" target="_tQh54Lk8EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_woG5sbk8EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_woG5srk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#04814dd4-94a5-43c8-bc83-f2f0f1f58c55?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_woG5s7k8EeuevZq3ZGZbnA" points="[0, 0, -49, -60]$[49, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_woHgwLk8EeuevZq3ZGZbnA" id="(0.6625,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yYIF0Lk8EeuevZq3ZGZbnA" id="(0.25,0.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_w6nmALk8EeuevZq3ZGZbnA" type="4001" source="_tQh54Lk8EeuevZq3ZGZbnA" target="_ua1J0Lk8EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_w6nmAbk8EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_w6nmArk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#2a44fb7e-6f3c-4d47-aba6-5357ec6d8741?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w6nmA7k8EeuevZq3ZGZbnA" points="[0, 0, 0, 164]$[0, -164, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_w6oNELk8EeuevZq3ZGZbnA" id="(0.5,0.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yYIs4Lk8EeuevZq3ZGZbnA" id="(0.4946236559139785,1.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_xpLVILk8EeuevZq3ZGZbnA" type="4001" source="_ua1J0Lk8EeuevZq3ZGZbnA" target="_sV9vELk8EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_xpLVIbk8EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_xpLVIrk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#dd32e714-5c8b-4fba-8662-e8a32fd3a4c9?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xpLVI7k8EeuevZq3ZGZbnA" points="[0, 0, 49, -60]$[-49, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xpL8MLk8EeuevZq3ZGZbnA" id="(0.24731182795698925,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yYIF0rk8EeuevZq3ZGZbnA" id="(0.6625,0.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_x5x88Lk8EeuevZq3ZGZbnA" type="4001" source="_sV9vELk8EeuevZq3ZGZbnA" target="_vggYcLk8EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_x5x88bk8EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_x5x88rk8EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#c3e2ccb6-6c58-439b-9c24-7265b6246375?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_x5x887k8EeuevZq3ZGZbnA" points="[0, 0, 47, -60]$[-47, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x5ykALk8EeuevZq3ZGZbnA" id="(0.325,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yYIF0bk8EeuevZq3ZGZbnA" id="(0.5,0.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_Ca0tYLk9EeuevZq3ZGZbnA" type="4001" source="_Ca0thLk9EeuevZq3ZGZbnA" target="_Ca0tnLk9EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_Ca0tYbk9EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_Ca0tYrk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#413c5ef6-398d-4da2-979a-268ba22416c5?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ca0tY7k9EeuevZq3ZGZbnA" points="[0, 0, 49, -60]$[-49, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tZLk9EeuevZq3ZGZbnA" id="(0.24731182795698925,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tZbk9EeuevZq3ZGZbnA" id="(0.6625,0.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_Ca0tcrk9EeuevZq3ZGZbnA" type="4001" source="_Ca0tnLk9EeuevZq3ZGZbnA" target="_Ca0GULk9EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_Ca0tc7k9EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_Ca0tdLk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#38fe3442-aa8e-40ec-ab38-62b004ce1d43?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ca0tdbk9EeuevZq3ZGZbnA" points="[0, 0, -49, -60]$[49, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tdrk9EeuevZq3ZGZbnA" id="(0.6625,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0td7k9EeuevZq3ZGZbnA" id="(0.25,0.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_Ca0tkLk9EeuevZq3ZGZbnA" type="4001" source="_Ca0GULk9EeuevZq3ZGZbnA" target="_Ca0thLk9EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_Ca0tkbk9EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_Ca0tkrk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#bc7f9440-dd96-419d-b5ed-ee3fc9a6424d?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ca0tk7k9EeuevZq3ZGZbnA" points="[0, 0, 0, 164]$[0, -164, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tlLk9EeuevZq3ZGZbnA" id="(0.5,0.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tlbk9EeuevZq3ZGZbnA" id="(0.4946236559139785,1.0)"/>
  </edges>
  <edges xmi:type="notation:Edge" xmi:id="_Ca0tlrk9EeuevZq3ZGZbnA" type="4001" source="_Ca0tnLk9EeuevZq3ZGZbnA" target="_Ca0tZrk9EeuevZq3ZGZbnA">
    <styles xmi:type="notation:RoutingStyle" xmi:id="_Ca0tl7k9EeuevZq3ZGZbnA"/>
    <styles xmi:type="notation:FontStyle" xmi:id="_Ca0tmLk9EeuevZq3ZGZbnA" fontName="Segoe UI"/>
    <element xmi:type="proc:Link" href="resource.proc#4397f238-8569-4b04-b37c-d276123bef9f?fileId=01ef66d2-a0a0-48b0-bfb6-a2c88aa4c2a4$type=proc?"/>
    <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ca0tmbk9EeuevZq3ZGZbnA" points="[0, 0, 47, -60]$[-47, 60, 0, 0]"/>
    <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tmrk9EeuevZq3ZGZbnA" id="(0.325,1.0)"/>
    <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Ca0tm7k9EeuevZq3ZGZbnA" id="(0.5,0.0)"/>
  </edges>
</notation:Diagram>
]]></diagram>
</proc:process>